### PR TITLE
safekeeper: refactor timeline initialization

### LINKED ISSUE #8927: "timeline x/y exists on disk, but wasn't loaded on startup" errors in safekeeper logs
We have $subject entries on staging, and sometimes they disappear after

```
timeline {} potential data loss: flush_lsn by find_end_of_wal is less than either commit_lsn or peer_horizon_lsn from control file
```
 is logged.

https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%22o1r%22%3A%7B%22datasource%22%3A%22xHHYY0dVz%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22expr%22%3A%22%7Bneon_service%3D%5C%22safekeeper%5C%22%2C+hostname+%3D%7E+%5C%22safekeeper-9.*%5C%22%7D+%7C%7E+%5C%221f6b205692feb56e4a870a80b4354124%7Cversion%3A+%5C%22%22%2C%22queryType%22%3A%22range%22%2C%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%22xHHYY0dVz%22%7D%2C%22editorMode%22%3A%22code%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%221723680000000%22%2C%22to%22%3A%221724457599000%22%7D%7D%7D&orgId=1

Investigation showed that

1) We miss control file persist on disk on timeline creation since this check was added:
```
        if s.eq(&*self.pers) {
            // nothing to do if state didn't change
        } else {
            self.pers.persist(s).await?;
        }
```

If safekeeper is restarted before any other activity persists the cf, it is lost, leading to errors in subject. It doesn't mean data loss because nothing was acknowledged on the safekeeper, but it refuses access to the timeline once this happens.

To also fix potential similar issue when safekeeper is restarted when timeline directory is created but nothing has been written yet, I propose to make timeline creation work similar to pull_timeline: first prepare everything (only cf so far) in temp directory and then atomically rename it.

2) Surprisingly, after many days of repeating errors timeline can self fix with 
```
timeline {} potential data loss: flush_lsn by find_end_of_wal is less than either commit_lsn or peer_horizon_lsn from control file
```

It is because timeline creation inserts its entry into global map indistinguishable from normal timeline. Normally it doesn't create any issues because timeline itself is locked during init, but if init fails something else might have already got Arc to it and attempt to do something. In the case I saw apparently broker task did `record_safekeeper_info`, persisting the control file, thus fixing it. It is better to block access to timeline while it is being created.

This logging also needs improvement, it at least needs LSNs. It is also safer to refuse to load if flush_lsn is less than commit_lsn, it indicates data corruption.

### PR DESCRIPTION
**Pull request by arssher**
Always do timeline init through atomic rename of temp directory. Add GlobalTimelines::load_temp_timeline which does this, and use it from both pull_timeline and basic timeline creation. Fixes a collection
of issues:
- previously timeline creation didn't really flushed cfile to disk
  due to 'nothing to do if state didn't change' check;
- even if it did, without tmp dir it is possible to lose the cfile
  but leave timeline dir in place, making it look corrupted;
- tenant directory creation fsync was missing in timeline creation;
- pull_timeline is now protected from concurrent both itself and
  timeline creation;
- now global timelines map entry got special CreationInProgress
  entry type which prevents from anyone getting access to timeline
  while it is being created (previously one could get access to it,
  but it was locked during creation, which is valid but confusing if
  creation failed).

fixes #8927

### CODE REVIEW

File: safekeeper/src/timelines_global_map.rs [hunk 1]
```diff
@@ -163,14 +165,13 @@ impl GlobalTimelines {
...
-                                let tli = Arc::new(timeline);
+                            Ok(tli) => {
                                 let mut shared_state = tli.write_shared_state().await;
                                 TIMELINES_STATE
                                     .lock()
                                     .unwrap()
                                     .timelines
-                                    .insert(ttid, tli.clone());
+                                    .insert(ttid, GlobalMapTimeline::Timeline(tli.clone()));
                                 tli.bootstrap(
```
Comment (VladLazar) [inline safekeeper/src/timelines_global_map.rs:175]: Shoudln't we bootstrap before adding the timeline to the global map or are `GlobalTimelines::get()` callers responsible for checking the status of the timeline? Doesn't make much difference if we don't wait on bootstrap to finish though.

File: safekeeper/src/state.rs [hunk 2]
```diff
@@ -91,8 +95,24 @@ impl TimelinePersistentState {
...
+            bail!(TimelineError::UninitializedWalSegSize(*ttid));
+        }
+
+        if server_info.pg_version == UNKNOWN_SERVER_VERSION {
+            bail!(TimelineError::UninitialinzedPgVersion(*ttid));
+        }
+
+        if commit_lsn < local_start_lsn {
+            bail!(
+                "commit_lsn {} is higher than local_start_lsn {}",
```
Comment (VladLazar) [inline safekeeper/src/state.rs:109]: You mean `smaller`, right?

File: safekeeper/src/timelines_global_map.rs [hunk 3]
```diff
@@ -282,55 +238,146 @@ impl GlobalTimelines {
...
-            // Bootstrap is transactional, so if it fails, the timeline will be deleted,
-            // and the state on disk should remain unchanged.
-            if let Err(e) = timeline
-                .init_new(
-                    &mut shared_state,
+        // TODO: currently we create only cfile. It would be reasonable to
+        // immediately initialize first WAL segment as well.
+        let state =
+            TimelinePersistentState::new(&ttid, server_info, vec![], commit_lsn, local_start_lsn)?;
+        control_file::FileStorage::create_new(tmp_dir_path.clone(), &conf, state).await?;
```
Comment (skyzh) [inline safekeeper/src/timelines_global_map.rs:248]: looking at the implementation of `create_new`, `sync_all` is not explicitly called for the control file? (I saw the directory got synced but it does not guarantee the persistence of the file content itself?)

**Review by skyzh — COMMENTED** [review]
Rest LGTM :)

File: safekeeper/src/timelines_global_map.rs [hunk 4]
```diff
@@ -31,13 +44,9 @@ struct GlobalTimelinesState {
 
     conf: Option<SafeKeeperConf>,
     broker_active_set: Arc<TimelinesSet>,
-    load_lock: Arc<tokio::sync::Mutex<TimelineLoadLock>>,
```
[the remark this answers is not in the document]
Comment (arssher) [reply safekeeper/src/timelines_global_map.rs:34]: Yes, copy and pull were protected from each other (and themselves), but not from creation. Now they all go through CreationInProgress.

File: safekeeper/src/timelines_global_map.rs (hunk 1 above)
Comment (arssher) [reply safekeeper/src/timelines_global_map.rs:175]: Yes, the only thing it does is spawning manager task, so order doesn't matter.

File: safekeeper/src/state.rs (hunk 2 above)
Comment (arssher) [reply safekeeper/src/state.rs:109]: vups, indeed

File: safekeeper/src/timelines_global_map.rs (hunk 3 above)
Comment (arssher) [reply safekeeper/src/timelines_global_map.rs:248]: It is called `persist` (`impl Storage for FileStorage` does durable_rename, which fsyncs the file before (and after) rename.

**Review by VladLazar — APPROVED** [review]

**Review by skyzh — APPROVED** [review]
