### PR TITLE
fix(pageserver): add the walreceiver state to tenant timeline GET api endpoint

### LINKED ISSUE #3115: Create a timeline subcommand to print its walreceiver state
If walreceiver is stuck due to some reason, it might be simpler to send an HTTP GET query into pageserver management API instead of checking the logs for error messages.

New HTTP endpoint should return:
* all safekeepers whose messages were recently received from the broker
* Safekeepers' metadata, related to timeline: LSNs, last message time, etc.
* current active walreceiver connection metadata: SK id, time since connected, etc. or time since the last connection happened
* latest feedback message metadata? Latest lsn caught up to would be useful

### PR DESCRIPTION
**Pull request by duguorong009**
Add a `walreceiver_state` field to `TimelineInfo` (response of `GET /v1/tenant/:tenant_id/timeline/:timeline_id`) and while doing that, refactor out a common `Timeline::walreceiver_state(..)`. No OpenAPI changes, because this is an internal debugging addition.

Fixes #3115.

### CODE REVIEW

**Review by koivunej — CHANGES_REQUESTED** [review]
Otherwise this is looking good but I see I have failed to update the issue description and only requested this in my follow-up comment much later.

Could you move it to be part of `pageserver::http::routes::timeline_detail_handler` or `GET /v1/tenant/:tenant/timeline/:timeline` instead of a new endpoint? In pratice with prod, timeline detail is what we most often get, that way it would be easily accessible for all "existing users".

File: pageserver/src/http/routes.rs [hunk 1]
```diff
@@ -437,6 +437,39 @@ async fn timeline_detail_handler(
...
+
+        let walreceiver_status = {
+            match &*timeline.walreceiver.lock().unwrap() {
+                None => "stopping or stopped".to_string(),
+                Some(walreceiver) => match walreceiver.status() {
+                    Some(status) => status.to_human_readable_string(),
+                    None => "Not active".to_string(),
+                },
+            }
+        };
```
Comment (koivunej) [inline pageserver/src/http/routes.rs:463]: Feels like this repeats some code we already have in Timeline, perhaps with `Timeline::wait_lsn`. Perhaps we could move the common parts as `Timeline::walreceiver_status(&self) -> String`?

Comment (duguorong009) [reply pageserver/src/http/routes.rs:463]: Yes, that is good idea. @koivunej 
Will update the code as recommended.

**Comment by duguorong009** [comment]
> Otherwise this is looking good but I see I have failed to update the issue description and only requested this in my follow-up comment much later.
> 
> Could you move it to be part of `pageserver::http::routes::timeline_detail_handler` or `GET /v1/tenant/:tenant/timeline/:timeline` instead of a new endpoint? In pratice with prod, timeline detail is what we most often get, that way it would be easily accessible for all "existing users".

@koivunej 
I updated the PR as you recommend. (Thanks for tips!)
Please re-check the PR, and give me the comments.

File: pageserver/src/tenant/timeline/walreceiver.rs [hunk 2]
```diff
@@ -135,7 +135,7 @@ impl WalReceiver {
         .await;
     }
 
-    pub(super) fn status(&self) -> Option<ConnectionManagerStatus> {
+    pub fn status(&self) -> Option<ConnectionManagerStatus> {
```
Comment (koivunej) [inline pageserver/src/tenant/timeline/walreceiver.rs:138]:
```suggestion
    pub(crate) fn status(&self) -> Option<ConnectionManagerStatus> {
```

File: pageserver/src/tenant/timeline.rs [hunk 3]
```diff
@@ -607,6 +599,16 @@ impl Timeline {
         }
     }
 
+    pub fn walreceiver_status(&self) -> String {
```
Comment (koivunej) [inline pageserver/src/tenant/timeline.rs:602]:
```suggestion
    pub(crate) fn walreceiver_status(&self) -> String {
```

**Review by koivunej — APPROVED** [review]
Yeah apologies on the openapi changes, which were good but as we'll need this for debugging, I don't think it is important to note this here.

Let's make the new methods pub(crate) and I'll fire up a workflow run for this. I can most likely merge those commits, let's try.

**Comment by koivunej** [comment]
Thanks for working on this as well!

I added those `pub(crate)` and can fix up if these cause any issues. `pub(crate)` will make it visible (compilter warning) if these functions were to become unused later.

Hmm.. Looks like I don't have to make a separate workflow for this now that I've commited to it, which is nice.

**Comment by duguorong009** [comment]
Thanks for the fixture commit! @koivunej 

BTW, can you check the issue #5131 and give some comments? 
Or, at least, you let @problame know?
Thanks in advance!

**Comment by duguorong009** [comment]
> Thanks for working on this as well!
> 
> I added those `pub(crate)` and can fix up if these cause any issues. `pub(crate)` will make it visible (compiler warning) if these functions were to become unused later.
> 
> Hmm.. ~Looks like I don't have to make a separate workflow for this now that I've commited to it, which is nice.~ Nope, still need to create one, but will handle that after seeing that my suggestions still compile.

Yes, for me, the CI run is a bit inconvenient.
Also, I just do the `cargo test` for local testing of PR.

**Comment by koivunej** [comment]
> Yes, for me, the CI run is a bit inconvenient. Also, I just do the `cargo test` for local testing of PR.

It's a bit inconvenient for everyone, but especially for external contributors :) `cargo test` is fine with rust tests.

Python tests take quite some time and requrie a beefy cpu, preferably an isolated box. I usually run them with `./scripts/pytest -n16 -vv --tb=short -k 'debug-pg14'` after a `cargo build_testing`, but ... for these rust refactorings there should be no need.
