### PR TITLE
fix: replace all `std::PathBuf`s with `camino::Utf8PathBuf`

### LINKED ISSUE #4689: Replace PathBufs with camino
We shouldn't in general have non-utf8 paths anywhere, like with `RemotePath::object_name` they scare me because it's not that the object has no name, it could also be that it fails to convert to str. See https://github.com/neondatabase/neon/blob/92aee7e07f347a0cc125462705811963ab5c78e9/libs/remote_storage/src/lib.rs#L66-L68

Instead of directly using `std::path::PathBuf`, we should use https://docs.rs/camino/latest/camino/. It's not like we could ever even read a non-utf8 path from a config file; we could only read them from command line arguments or environment (`std::env::var_os` -- luckily only used in `neon_local` and `postgres_ffi`) .

This is a rather large change, yielding hopefully tiny amount of touching everything in pageserver as we use a plenty of PathBufs or otherwise preformatted path names for things which have structured names and `libs/remote_storage`, and it's users (at least safekeeper).

Most likely there is a path to fix this in multiple separate PRs.

### PR DESCRIPTION
**Pull request by duguorong009**
Fixes #4689 by replacing all of `std::Path` , `std::PathBuf` with `camino::Utf8Path`, `camino::Utf8PathBuf` in
- pageserver
- safekeeper
- control_plane
- libs/remote_storage

### CODE REVIEW

**Comment by save-buffer** [comment]
@koivunej please take a look

File: libs/remote_storage/src/lib.rs [hunk 1]
```diff
@@ -48,16 +48,16 @@ const REMOTE_STORAGE_PREFIX_SEPARATOR: char = '/';
 /// The prefix is an implementation detail, that allows representing local paths
 /// as the remote ones, stripping the local storage prefix away.
 #[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
-pub struct RemotePath(PathBuf);
+pub struct RemotePath(Utf8PathBuf);
 
 impl std::fmt::Display for RemotePath {
     fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
-        write!(f, "{}", self.0.display())
+        write!(f, "{}", self.0.as_std_path().display())
```
Comment (koivunej) [inline libs/remote_storage/src/lib.rs:55]: Utf8Path and Utf8PathBuf `impl std::fmt:Display`, so this could be just:

```suggestion
        std::fmt::Display::fmt(&self.0, f)
```

File: libs/remote_storage/src/lib.rs [hunk 2]
```diff
@@ -284,7 +284,10 @@ impl GenericRemoteStorage {
     pub fn from_config(storage_config: &RemoteStorageConfig) -> anyhow::Result<Self> {
         Ok(match &storage_config.storage {
             RemoteStorageKind::LocalFs(root) => {
-                info!("Using fs root '{}' as a remote storage", root.display());
+                info!(
+                    "Using fs root '{}' as a remote storage",
+                    root.as_std_path().display()
+                );
```
Comment (koivunej) [inline libs/remote_storage/src/lib.rs:290]:
```suggestion
                info!(
                    "Using fs root '{root}' as a remote storage",
                );
```

Unless I am mistaken.

File: libs/remote_storage/src/local_fs.rs [hunk 3]
```diff
@@ -28,29 +23,32 @@ const LOCAL_FS_TEMP_FILE_SUFFIX: &str = "___temp";
...
         if !storage_root.is_absolute() {
-            storage_root = storage_root.canonicalize().with_context(|| {
-                format!("Failed to represent path {storage_root:?} as an absolute path")
-            })?;
+            storage_root = storage_root
+                .canonicalize()
+                .with_context(|| {
+                    format!("Failed to represent path {storage_root:?} as an absolute path")
+                })
+                .map(|pb| Utf8PathBuf::from_path_buf(pb).unwrap())?;
```
Comment (koivunej) [inline libs/remote_storage/src/local_fs.rs:44]: Perhaps https://docs.rs/camino/latest/camino/struct.Utf8Path.html#method.canonicalize_utf8 should be used here?

File: libs/remote_storage/src/local_fs.rs [hunk 4]
```diff
@@ -59,22 +57,22 @@ impl LocalFs {
...
+        file_path: &Utf8Path,
     ) -> anyhow::Result<Option<StorageMetadata>> {
-        let metadata_path = storage_metadata_path(file_path);
+        let metadata_path = storage_metadata_path(file_path)?;
         if metadata_path.exists() && metadata_path.is_file() {
             let metadata_string = fs::read_to_string(&metadata_path).await.with_context(|| {
                 format!(
                     "Failed to read metadata from the local storage at '{}'",
-                    metadata_path.display()
+                    metadata_path.as_std_path().display()
```
Comment (koivunej) [inline libs/remote_storage/src/local_fs.rs:67]: No need to go to std pathbuf here either because Utf8Path `impl std::fmt::Display`.

File: libs/remote_storage/src/local_fs.rs [hunk 5]
```diff
@@ -171,23 +169,22 @@ impl RemoteStorage for LocalFs {
...
+        // Note that Utf8PathBuf starts_with only considers full path segments, but
         // object prefixes are arbitrary strings, so we need the strings for doing
         // starts_with later.
-        let prefix = full_path.to_string_lossy();
+        let prefix = full_path.to_string();
 
         let mut files = vec![];
         let mut directory_queue = vec![initial_dir.clone()];
         while let Some(cur_folder) = directory_queue.pop() {
             let mut entries = fs::read_dir(cur_folder.clone()).await?;
```
Comment (koivunej) [inline libs/remote_storage/src/local_fs.rs:180]: Camino would have it's own https://docs.rs/camino/latest/camino/struct.Utf8Path.html#method.read_dir_utf8 which allows "internal translation" which I think would be enough here.

File: libs/utils/src/fs_ext.rs [hunk 6]
```diff
@@ -75,7 +75,8 @@ mod test {
         );
 
         // invoke on a file to ensure it returns an error
-        let file_path: PathBuf = dir_path.join("testfile");
+        let file_path: Utf8PathBuf =
+            Utf8PathBuf::from_path_buf(dir_path.join("testfile")).expect("non-Unicode path");
```
Comment (koivunej) [inline libs/utils/src/fs_ext.rs:79]: I wonder if it would make sense in this module to have a custom `tempdir()` which would return something which we know there is a Utf8PathBuf?

It would appear that the `tempfile::Builder` will always create an ascii paths.

Also, the author of camino has `camino_tempfile` which would already have the utilities. If I recall correclty, the tempfile==3.5.0 is what we depend on right now.

File: libs/utils/src/lsn.rs [hunk 7]
```diff
@@ -44,10 +44,10 @@ impl Lsn {
     /// Parse an LSN from a filename in the form `0000000000000000`
     pub fn from_filename<F>(filename: F) -> Result<Self, LsnParseError>
     where
-        F: AsRef<Path>,
+        F: AsRef<Utf8Path>,
     {
-        let filename: &Path = filename.as_ref();
-        let filename = filename.to_str().ok_or(LsnParseError)?;
+        let filename: &Utf8Path = filename.as_ref();
+        let filename = filename.as_std_path().to_str().ok_or(LsnParseError)?;
```
Comment (koivunej) [inline libs/utils/src/lsn.rs:50]: There is https://docs.rs/camino/1.1.6/camino/struct.Utf8Path.html#method.as_str which seems applicable here instead of the fallible std::path::Path route?

File: pageserver/ctl/src/main.rs [hunk 8]
```diff
@@ -90,19 +91,20 @@ async fn main() -> anyhow::Result<()> {
             layer_map_analyzer::main(&cmd).await?;
         }
         Commands::PrintLayerFile(cmd) => {
-            if let Err(e) = read_pg_control_file(&cmd.path) {
+            let cmd_path = Utf8PathBuf::from_path_buf(cmd.path).expect("non-Unicode path");
```
Comment (koivunej) [inline pageserver/ctl/src/main.rs:94]: I wonder for pagectl if the camino's Path could be used as part of those subcommand arguments already, to do less conversions down the line?

**Review by koivunej — CHANGES_REQUESTED** [review]
I think this is looking very complete.

In many places we should avoid the conversion https://docs.rs/camino/1.1.6/camino/struct.Utf8Path.html#method.as_std_path to call `display` on it because the camino path is already backed up by a `str` which can be just formatted right away.

Similarly the https://doc.rust-lang.org/stable/std/ffi/struct.OsStr.html#method.to_str and https://doc.rust-lang.org/stable/std/ffi/struct.OsStr.html#method.to_string_lossy should now be completly avoidable, because there is no conversion.

File: libs/utils/src/fs_ext.rs (hunk 6 above)
Comment (duguorong009) [reply libs/utils/src/fs_ext.rs:79]: Hmm, you mean that we should replace the `tempfile` crate with `camino_tempfile` crate.
And update the related codes? @koivunej

Comment (koivunej) [reply libs/utils/src/fs_ext.rs:79]: Earlier me:

> I wonder if it would make sense in this module to have a custom tempdir() which would return something which we know there is a Utf8PathBuf?

Looking around, we do have plenty of usages for `tempfile::tempdir` in tests.

I was initially thinking of if this should be added into this tests module:

```patch
+    fn tempdir() -> Utf8Tempdir {
+        // FIXME: this could be solved with camino_tempfile dependency
+        let dir = tempfile::tempdir().unwrap();
+        Utf8Tempdir::new(dir)
+    }
+
+    struct Utf8Tempdir(tempfile::TempDir);
+
+    impl Utf8Tempdir {
+        fn new(dir: tempfile::TempDir) -> Self {
+            let ret = Self(dir);
+            ret.path();
+            ret
+        }
+
+        fn path(&self) -> &camino::Utf8Path {
+            use camino::Utf8Path;
+            match Utf8Path::from_path(self.0.path()) {
+                Some(p) => p,
+                None => {
+                    if Utf8Path::from_path(&std::env::temp_dir()).is_none() {
+                        panic!("std::env::temp_dir() is pointing to a non-utf8 directory so temporary directories on utf8 paths cannot be created")
+                    } else {
+                        unreachable!("tempfile::tempdir should create ascii paths but the std::env::temp_dir() is utf-8")
+                    }
+                }
+            }
+        }
+    }
```

But this is exactly what `camino_tempfile` provides, with adjusted docs.

I think it would make sense to use it. It would allow getting rid of repeated conversion code.

File: libs/remote_storage/src/s3_bucket.rs [hunk 9]
```diff
@@ -144,7 +144,7 @@ impl S3Bucket {
         assert_eq!(std::path::MAIN_SEPARATOR, REMOTE_STORAGE_PREFIX_SEPARATOR);
         let path_string = path
             .get_path()
-            .to_string_lossy()
+            .to_string()
             .trim_end_matches(REMOTE_STORAGE_PREFIX_SEPARATOR)
             .to_string();
```
Comment (koivunej) [inline libs/remote_storage/src/s3_bucket.rs:149]: Now noticed that this looks odd.

First `to_string` should probably be `Utf8PathBuf::as_str`.

Second `to_string` is not needed at all.

This is semi-unrelated, but I it was required before to use the `+` operator because before the `to_string_lossy` returned a `Cow<'_, str>`..

File: libs/utils/src/crashsafe.rs [hunk 10]
```diff
@@ -44,7 +46,7 @@ pub fn create_dir_all(path: impl AsRef<Path>) -> io::Result<()> {
             None => {
                 return Err(io::Error::new(
                     io::ErrorKind::InvalidInput,
-                    format!("can't find parent of path '{}'", path.display()).as_str(),
+                    format!("can't find parent of path '{path}'",).as_str(),
```
Comment (koivunej) [inline libs/utils/src/crashsafe.rs:49]:
```suggestion
                    format!("can't find parent of path '{path}'"),
```

Seems this `as_str` removal is also unrelated, but it's not needed.

File: libs/utils/src/crashsafe.rs [hunk 11]
```diff
@@ -79,12 +81,15 @@ pub fn path_with_suffix_extension(original_path: impl AsRef<Path>, suffix: &str)
...
     };
-    original_path
-        .as_ref()
-        .with_extension(new_extension.as_ref())
+    Utf8PathBuf::from_path_buf(
+        original_path
+            .as_ref()
+            .with_extension(new_extension.as_ref()),
+    )
+    .expect("non-Unicode path")
```
Comment (koivunej) [inline libs/utils/src/crashsafe.rs:89]: To statically avoid this would require `original_path` to instead be `AsRef<Utf8Path>`. Have you explored what would that require? Looking at the pageserver changes at least, you've already changed all paths in PageserverConf, so I cannot really see where would these `std::path::Path` appear anymore for pageserver.

Seems the changes are not drastic:

```patch
diff --git a/libs/utils/src/crashsafe.rs b/libs/utils/src/crashsafe.rs
index 9a4c36f0b..dae6df90e 100644
--- a/libs/utils/src/crashsafe.rs
+++ b/libs/utils/src/crashsafe.rs
@@ -72,21 +72,15 @@ pub fn create_dir_all(path: impl AsRef<Utf8Path>) -> io::Result<()> {

 /// Adds a suffix to the file(directory) name, either appending the suffix to the end of its extension,
 /// or if there's no extension, creates one and puts a suffix there.
-pub fn path_with_suffix_extension(original_path: impl AsRef<Path>, suffix: &str) -> Utf8PathBuf {
-    let new_extension = match original_path
-        .as_ref()
-        .extension()
-        .map(OsStr::to_string_lossy)
-    {
+pub fn path_with_suffix_extension(
+    original_path: impl AsRef<Utf8Path>,
+    suffix: &str,
+) -> Utf8PathBuf {
+    let new_extension = match original_path.as_ref().extension() {
         Some(extension) => Cow::Owned(format!("{extension}.{suffix}")),
         None => Cow::Borrowed(suffix),
     };
-    Utf8PathBuf::from_path_buf(
-        original_path
-            .as_ref()
-            .with_extension(new_extension.as_ref()),
-    )
-    .expect("non-Unicode path")
+    original_path.as_ref().with_extension(&new_extension)
 }

 pub fn fsync_file_and_parent(file_path: &Utf8Path) -> io::Result<()> {
diff --git a/pageserver/src/tenant/mgr.rs b/pageserver/src/tenant/mgr.rs
index ef33afca1..d1c698206 100644
--- a/pageserver/src/tenant/mgr.rs
+++ b/pageserver/src/tenant/mgr.rs
@@ -70,12 +70,12 @@ impl TenantsMap {
 ///
 /// This is pageserver-specific, as it relies on future processes after a crash to check
 /// for TEMP_FILE_SUFFIX when loading things.
-async fn safe_remove_tenant_dir_all(path: impl AsRef<Path>) -> std::io::Result<()> {
+async fn safe_remove_tenant_dir_all(path: impl AsRef<Utf8Path>) -> std::io::Result<()> {
     let tmp_path = safe_rename_tenant_dir(path).await?;
     fs::remove_dir_all(tmp_path).await
 }

-async fn safe_rename_tenant_dir(path: impl AsRef<Path>) -> std::io::Result<Utf8PathBuf> {
+async fn safe_rename_tenant_dir(path: impl AsRef<Utf8Path>) -> std::io::Result<Utf8PathBuf> {
     let parent = path
         .as_ref()
         .parent()
@@ -92,7 +92,7 @@ async fn safe_rename_tenant_dir(path: impl AsRef<Path>) -> std::io::Result<Utf8P
         .collect::<String>()
         + TEMP_FILE_SUFFIX;
     let tmp_path = path_with_suffix_extension(&path, &rand_suffix);
-    fs::rename(&path, &tmp_path).await?;
+    fs::rename(path.as_ref(), &tmp_path).await?;
     fs::File::open(parent).await?.sync_all().await?;
     Ok(tmp_path)
 }
```

File: pageserver/src/tenant.rs [hunk 12]
```diff
@@ -1012,41 +1012,30 @@ impl Tenant {
...
-                    timeline_uninit_mark_file.display()
+                    "Found an uninit mark file {timeline_uninit_mark_file}, removing the timeline and its uninit mark",
                 );
-                let timeline_id = TimelineId::try_from(timeline_uninit_mark_file.file_stem())
-                    .with_context(|| {
-                        format!(
-                            "Could not parse timeline id out of the timeline uninit mark name {}",
-                            timeline_uninit_mark_file.display()
+                let timeline_id =
+                    TimelineId::try_from(timeline_uninit_mark_file.as_std_path().file_stem())
```
Comment (koivunej) [inline pageserver/src/tenant.rs:1033]: There is also https://docs.rs/camino/latest/camino/struct.Utf8Path.html#method.file_stem so I don't see why this would require the conversion?

File: safekeeper/src/wal_backup.rs [hunk 13]
```diff
@@ -408,10 +409,11 @@ pub async fn backup_lsn_range(
...
 async fn backup_single_segment(
     seg: &Segment,
-    timeline_dir: &Path,
-    workspace_dir: &Path,
+    timeline_dir: &Utf8Path,
+    workspace_dir: &Utf8Path,
 ) -> Result<Segment> {
-    let segment_file_path = seg.file_path(timeline_dir)?;
+    let segment_file_path = Utf8PathBuf::from_path_buf(seg.file_path(timeline_dir.as_std_path())?)
+        .expect("non-Unicode path");
```
Comment (koivunej) [inline safekeeper/src/wal_backup.rs:416]: If `Segment::file_path` operated on Utf8Path then this expect would be statically avoided.

File: pageserver/src/tenant/timeline.rs [hunk 14]
```diff
@@ -1697,7 +1697,8 @@ impl Timeline {
                         Discovered::Temporary(name) => (name, "temporary timeline file"),
                         Discovered::TemporaryDownload(name) => (name, "temporary download"),
                     };
-                    path.push(name);
+                    let name_path = name.to_str().map(Utf8Path::new).expect("non-Unicode path");
```
Comment (koivunej) [inline pageserver/src/tenant/timeline.rs:1700]: If `Timeline::init::scan_timeline_dir` would iterate over the directory with `Utf8Path::read_dir_utf8` and have `enum Decision` carry `String` instead of `OsString` this would be statically avoided.

File: pageserver/src/tenant/timeline.rs [hunk 15]
```diff
@@ -4734,11 +4732,11 @@ fn is_send() {
...
 /// Add a suffix to a layer file's name: .{num}.old
 /// Uses the first available num (starts at 0)
-fn rename_to_backup(path: &Path) -> anyhow::Result<()> {
+fn rename_to_backup(path: &Utf8Path) -> anyhow::Result<()> {
     let filename = path
         .file_name()
-        .ok_or_else(|| anyhow!("Path {} don't have a file name", path.display()))?
-        .to_string_lossy();
+        .ok_or_else(|| anyhow!("Path {path} don't have a file name",))?
+        .to_string();
```
Comment (koivunej) [inline pageserver/src/tenant/timeline.rs:4739]:
```suggestion
        .ok_or_else(|| anyhow!("Path {path} don't have a file name",))?;
```

If I understand correctly, this would be perfectly fine with `let filename` being a `&str`.

**Review by koivunej — CHANGES_REQUESTED** [review]
Found some suggestions to avoid the added `expect`'s. So far it has not seemed that we require adding new ones so we should avoid them if  possible. If there is some tricky, please highlight it and we'll discuss.

File: libs/remote_storage/src/s3_bucket.rs (hunk 9 above)
Comment (duguorong009) [reply libs/remote_storage/src/s3_bucket.rs:149]: Yes, it is right that first `to_string` is, in fact, `as_str`.
But, we need second `to_string` since return type is `String`.
Or we can add this `to_string` in `match::None` statement.

File: pageserver/src/tenant.rs (hunk 12 above)
Comment (duguorong009) [reply pageserver/src/tenant.rs:1033]: Um, currently, only `TryFrom<Option<&OsStr>>` is implemented for `TimelineId`.
That's why I added the conversion.
But, maybe, we can add/update the `TryFrom` impl for `TimelineId`, and use the `Utf8Path::file_stem()` in above case.

File: safekeeper/src/wal_backup.rs (hunk 13 above)
Comment (duguorong009) [reply safekeeper/src/wal_backup.rs:416]: Hmm, seems like I missed this part. :cold_sweat:

File: pageserver/src/tenant.rs (hunk 12 above)
Comment (duguorong009) [reply pageserver/src/tenant.rs]: I added the impl of `TryFrom<Option<&str>>` for `TimelineId`.
So, we can use the `Utf8Path::file_stem()` in above case.

File: Cargo.lock [hunk 16]
```diff
@@ -798,6 +798,22 @@ dependencies = [
...
 ]
 
+[[package]]
+name = "camino"
+version = "1.1.6"
+source = "registry+https://github.com/rust-lang/crates.io-index"
+checksum = "c59e92b5a388f549b863a7bea62612c09f24c8393560709a54558a9abdfb3b9c"
+
+[[package]]
+name = "camino-tempfile"
```
[the remark this answers is not in the document]
Comment (koivunej) [reply Cargo.lock:808]: > Low # of stars: 6

yep yep :D I will resolve this after doing a full round of auditing for these both.

**Review by koivunej — APPROVED** [review]
This is looking good, and this is a lot of changes! As chatted, there will be conflicts but as long as you have allowed changes from maintainers, I can push them in.

File: pageserver/Cargo.toml [hunk 17]
```diff
@@ -17,6 +17,8 @@ async-stream.workspace = true
 async-trait.workspace = true
 byteorder.workspace = true
 bytes.workspace = true
+camino.workspace = true
+camino-tempfile.workspace = true
```
Comment (koivunej) [inline pageserver/Cargo.toml:21]: Note for myself, need to understand why this was added.

Comment (koivunej) [reply pageserver/Cargo.toml:21]: Aah nevermind you just ordered it in alphabetical order.

File: pageserver/src/lib.rs [hunk 18]
```diff
@@ -125,25 +124,25 @@ pub const TIMELINE_DELETE_MARK_SUFFIX: &str = "___delete";
 /// Full path: `tenants/<tenant_id>/___ignored_tenant`.
 pub const IGNORED_TENANT_FILE_NAME: &str = "___ignored_tenant";
 
-pub fn is_temporary(path: &Path) -> bool {
+pub fn is_temporary(path: &Utf8Path) -> bool {
     match path.file_name() {
-        Some(name) => name.to_string_lossy().ends_with(TEMP_FILE_SUFFIX),
+        Some(name) => name.to_string().ends_with(TEMP_FILE_SUFFIX),
```
Comment (koivunej) [inline pageserver/src/lib.rs:129]:
```suggestion
        Some(name) => name.as_str().ends_with(TEMP_FILE_SUFFIX),
```

File: pageserver/src/lib.rs [hunk 19]
```diff
@@ -125,25 +124,25 @@ pub const TIMELINE_DELETE_MARK_SUFFIX: &str = "___delete";
...
         None => false,
     }
 }
 
-fn ends_with_suffix(path: &Path, suffix: &str) -> bool {
+fn ends_with_suffix(path: &Utf8Path, suffix: &str) -> bool {
     match path.file_name() {
-        Some(name) => name.to_string_lossy().ends_with(suffix),
+        Some(name) => name.to_string().ends_with(suffix),
```
Comment (koivunej) [inline pageserver/src/lib.rs:136]:
```suggestion
        Some(name) => name.as_str().ends_with(suffix),
```

**Review by koivunej — APPROVED** [review]
Few more suggestions, this is looking good.

File: pageserver/src/deletion_queue/list_writer.rs [hunk 20]
```diff
@@ -243,21 +236,19 @@ impl ListWriter {
             let file_name = dentry.file_name();
             let dentry_str = file_name.to_string_lossy();
 
-            if Some(file_name.as_os_str()) == header_path.file_name() {
+            if file_name.to_str() == header_path.file_name() {
```
Comment (koivunej) [inline pageserver/src/deletion_queue/list_writer.rs:239]: Unsure about this, I think there should be a PartialEq for OsStr and str?

Comment (koivunej) [reply pageserver/src/deletion_queue/list_writer.rs:239]: Perhaps all read_dir users need to be go over after this PR, no need to change yet.

**Comment by koivunej** [comment]
Quick auditing report:
- `camino` at https://github.com/camino-rs/camino (main)
- `camino-tempfile` at https://github.com/camino-rs/camino-tempfile (main)

`camino` has a lot of code, because of delegations and extensive documentation. Interesting parts like ancestors just reuse `std::path::Path` implementation with the (valid) assumption that delegated ancestors iterator does not magically create new non-utf8 sequences out of otherwise valid utf8 strings. Similar assumptions are seen elsewhere and are in the form of `unsafe { Utf8Path::assume_utf8(x) }`.

`camino-tempfile` wraps `tempfile` which we were already using in an expected and already discussed way on this PR but just with high quality documentation (assumed, did not really compare) and API error mapping.

File: Cargo.lock (hunk 16 above)
[the remark this answers is not in the document]
Comment (koivunej) [reply Cargo.lock:808]: https://github.com/neondatabase/neon/pull/5352#issuecomment-1736852357

**Comment by koivunej** [comment]
> https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5393/6322581419/index.html#suites/7d6bd76a6271bcc8c5c8cc94b5129e1c/8aa537493ede18d1

I think this error means that clap needs to use Utf8PathBuf instead of PathBuf. Most likely all other cli args structs as well.

**Comment by duguorong009** [comment]
> > https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5393/6322581419/index.html#suites/7d6bd76a6271bcc8c5c8cc94b5129e1c/8aa537493ede18d1
> 
> I think this error means that clap needs to use Utf8PathBuf instead of PathBuf. Most likely all other cli args structs as well. Or just safekeeper because it sounds like it's the cause of all test failures.

Based on your observation, I checked the `safekeeper` code.
And I found that this `opt_pathbuf_parser` was still parsing the `str` to `PathBuf`, not `Utf8PathBuf`.
I think that is the issue & pushed the patch commit.

File: pageserver/src/deletion_queue/list_writer.rs (hunk 20 above)
Comment (koivunej) [reply pageserver/src/deletion_queue/list_writer.rs]: This was in [955c1c7](https://github.com/neondatabase/neon/pull/5352/commits/955c1c728ead0cbfce4ec4b52a516a3f2e486681).

It's probably good right now.

**Comment by koivunej** [comment]
> #### Failures on Postgres 16
> 
> * `test_partial_evict_tenant`: [debug](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5393/6323530158/index.html#suites/0e58fb04d9998963e98e45fe1880af7d/493bfe16977bfdfc)

I just merged a flakyness fix, maybe merge main again?

 
> * `test_remote_storage_backup_and_restore[True-local_fs]`: [release](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5393/6323530158/index.html#suites/837740b64a53e769572c4ed7b7a7eeeb/a2733621fdb4773a), [debug](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5393/6323530158/index.html#suites/837740b64a53e769572c4ed7b7a7eeeb/c2e7722770f5da35)
> 
> 
> #### Failures on Postgres 15
> 
> * `test_remote_storage_backup_and_restore[True-local_fs]`: [release](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5393/6323530158/index.html#suites/837740b64a53e769572c4ed7b7a7eeeb/5138ee257a4276f3), [debug](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5393/6323530158/index.html#suites/837740b64a53e769572c4ed7b7a7eeeb/bdc54076825b84af)
> 
> 
> #### Failures on Postgres 14
> 
> * `test_remote_storage_backup_and_restore[True-local_fs]`: [release](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5393/6323530158/index.html#suites/837740b64a53e769572c4ed7b7a7eeeb/427b34c262f91fb5), [debug](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-5393/6323530158/index.html#suites/837740b64a53e769572c4ed7b7a7eeeb/9ebcfeab58f59000)

These need further investigation.

**Comment by duguorong009** [comment]
After merging main branch, `test_parital_evict_tenant` test passes.
Others still do not pass. 
One interesting point is that the `test_remote_storage_backup_and_restore` test passes on 
variants of `False-local_fs`, and `s3`.
Keep investigating the issue.

**Review by koivunej — APPROVED** [review]

File: libs/remote_storage/src/local_fs.rs [hunk 21]
```diff
@@ -171,23 +162,19 @@ impl RemoteStorage for LocalFs {
             }
         }
 
-        // Note that PathBuf starts_with only considers full path segments, but
+        // Note that Utf8PathBuf starts_with only considers full path segments, but
         // object prefixes are arbitrary strings, so we need the strings for doing
         // starts_with later.
-        let prefix = full_path.to_string_lossy();
+        let prefix = full_path.to_string();
```
Comment (koivunej) [inline libs/remote_storage/src/local_fs.rs:168]:
```suggestion
        let prefix = full_path.as_str();
```

This should still work? Did not test.

File: libs/remote_storage/src/local_fs.rs [hunk 22]
```diff
@@ -171,23 +162,19 @@ impl RemoteStorage for LocalFs {
...
-                let full_file_name = cur_folder.clone().join(&file_name);
-                if full_file_name
-                    .to_str()
-                    .map(|s| s.starts_with(prefix.as_ref()))
-                    .unwrap_or(false)
-                {
+            let mut entries = cur_folder.read_dir_utf8()?;
+            while let Some(Ok(entry)) = entries.next() {
+                let file_name = entry.file_name();
+                let full_file_name = cur_folder.clone().join(file_name);
```
Comment (koivunej) [inline libs/remote_storage/src/local_fs.rs:176]:
```suggestion
                let full_file_name = cur_folder.join(file_name);
```

I would expect this clone to be unnecessary, unless you just removed it in the previous push, because `Path::join` creates a new pathbuf, it seems it's similar to in camino.

File: libs/remote_storage/src/local_fs.rs [hunk 23]
```diff
@@ -171,23 +162,19 @@ impl RemoteStorage for LocalFs {
...
+                if full_file_name.to_string().starts_with(&prefix) {
```
Comment (koivunej) [inline libs/remote_storage/src/local_fs.rs:177]:
```suggestion
                if full_file_name.as_str().starts_with(&prefix) {
```

File: libs/remote_storage/src/local_fs.rs [hunk 24]
```diff
@@ -393,16 +373,16 @@ impl RemoteStorage for LocalFs {
     }
 }
 
-fn storage_metadata_path(original_path: &Path) -> PathBuf {
-    path_with_suffix_extension(original_path, "metadata")
+fn storage_metadata_path(original_path: &Utf8Path) -> anyhow::Result<Utf8PathBuf> {
+    Ok(path_with_suffix_extension(original_path, "metadata"))
 }
```
Comment (koivunej) [inline libs/remote_storage/src/local_fs.rs:378]: This looks weird now that I think of it, is the result needed?

File: libs/remote_storage/src/local_fs.rs (hunk 23 above)
Comment (duguorong009) [reply libs/remote_storage/src/local_fs.rs]: Done https://github.com/neondatabase/neon/pull/5352/commits/b437516edf8ae9e85cc20ae78b77fb8ee003a981

File: libs/remote_storage/src/local_fs.rs (hunk 22 above)
Comment (duguorong009) [reply libs/remote_storage/src/local_fs.rs]: Done https://github.com/neondatabase/neon/pull/5352/commits/b437516edf8ae9e85cc20ae78b77fb8ee003a981

File: libs/remote_storage/src/local_fs.rs (hunk 21 above)
Comment (duguorong009) [reply libs/remote_storage/src/local_fs.rs]: Done https://github.com/neondatabase/neon/pull/5352/commits/b437516edf8ae9e85cc20ae78b77fb8ee003a981 (+ test)

File: libs/remote_storage/src/local_fs.rs (hunk 24 above)
Comment (koivunej) [reply libs/remote_storage/src/local_fs.rs:378]: Well, this is not important, it's only within local_fs.
