### PR TITLE
Fix issue in compaction code

### LINKED ISSUE #3192: Segmentation fault during the TPC-H workload
After https://github.com/neondatabase/neon/pull/3167 we were able to get a backtrace for a segfault.

## Steps to reproduce
```
CONNSTR=... # BENCHMARK_CAPTEST_TPCH_S10_CONNSTR, see Notion page or slack

while true; do for f in `find test_runner/performance/tpc-h/queries -name "*.sql" | sort -V`; do echo "running $f"; psql $CONNSTR -f $f > /dev/null; done; done
```

It could take a while (1-2-3 hours) to catch.

## Expected result
 No segfaults

## Actual result
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  neon_read_at_lsn (rnode=..., forkNum=MAIN_FORKNUM, blkno=1186, request_lsn=<optimized out>, request_latest=<optimized out>, buffer=0x7fdea2b2fc00 "\004") at pagestore_smgr.c:1898
#1  0x00007fdeaccd7493 in neon_read (reln=0x563768dcb5d8, forkNum=MAIN_FORKNUM, blkno=1186, buffer=0x7fdea2b2fc00 "\004") at pagestore_smgr.c:1954
#2  0x0000563768344dc1 in ReadBuffer_common (smgr=<optimized out>, relpersistence=<optimized out>, forkNum=<optimized out>, blockNum=<optimized out>, mode=<optimized out>, strategy=<optimized out>, hit=<optimized out>) at bufmgr.c:1029
#3  0x0000563768345542 in ReadBufferExtended (reln=0x7fde89c3efe8, forkNum=forkNum@entry=MAIN_FORKNUM, blockNum=blockNum@entry=1186, mode=mode@entry=RBM_NORMAL, strategy=<optimized out>) at bufmgr.c:782
#4  0x00005637680d409f in heapgetpage (sscan=sscan@entry=0x563768e63120, page=page@entry=1186) at heapam.c:523
#5  0x00005637680d46a7 in heapgettup_pagemode (scan=scan@entry=0x563768e63120, dir=ForwardScanDirection, nkeys=0, key=0x0) at heapam.c:1241
#6  0x00005637680d58de in heap_getnextslot (sscan=0x563768e63120, direction=<optimized out>, slot=0x563768e054e8) at heapam.c:1519
#7  0x000056376823bb4a in table_scan_getnextslot (slot=0x563768e054e8, direction=ForwardScanDirection, sscan=<optimized out>) at ../../../src/include/access/tableam.h:1044
#8  SeqNext (node=0x563768e05348) at nodeSeqscan.c:80
#9  0x00005637682185ff in ExecScan (node=0x563768e05348, accessMtd=0x56376823bac0 <SeqNext>, recheckMtd=0x56376823ba90 <SeqRecheck>) at execScan.c:199
#10 0x000056376823d597 in ExecProcNode (node=0x563768e05348) at ../../../src/include/executor/executor.h:257
#11 buildSubPlanHash (econtext=0x563768e10fe8, node=0x563768e11df8) at nodeSubplan.c:570
#12 ExecHashSubPlan (isNull=0x563768e11d6d, econtext=0x563768e10fe8, node=0x563768e11df8) at nodeSubplan.c:118
#13 ExecSubPlan (node=node@entry=0x563768e11df8, econtext=econtext@entry=0x563768e10fe8, isNull=0x563768e11d6d) at nodeSubplan.c:87
#14 0x000056376820c337 in ExecEvalSubPlan (econtext=0x563768e10fe8, op=<optimized out>, state=0x563768e11d68) at execExprInterp.c:3932
#15 ExecInterpExpr (state=0x563768e11d68, econtext=0x563768e10fe8, isnull=<optimized out>) at execExprInterp.c:1564
#16 0x00005637682185b3 in ExecEvalExprSwitchContext (isNull=0x7ffcf6a5371f, econtext=0x563768e10fe8, state=0x563768e11d68) at ../../../src/include/executor/executor.h:339
#17 ExecQual (econtext=0x563768e10fe8, state=0x563768e11d68) at ../../../src/include/executor/executor.h:408
#18 ExecScan (node=0x563768e10dd8, accessMtd=0x563768230260 <IndexOnlyNext>, recheckMtd=0x56376805a94d <IndexOnlyRecheck>) at execScan.c:227
#19 0x000056376822e943 in ExecProcNode (node=0x563768e10dd8) at ../../../src/include/executor/executor.h:257
#20 ExecParallelHashJoinPartitionOuter (hjstate=0x563768e10aa8) at nodeHashjoin.c:1405
#21 ExecHashJoinImpl (parallel=true, pstate=0x563768e10aa8) at nodeHashjoin.c:328
#22 ExecParallelHashJoin (pstate=0x563768e10aa8) at nodeHashjoin.c:607
#23 0x000056376823c868 in ExecProcNode (node=0x563768e10aa8) at ../../../src/include/executor/executor.h:257
#24 ExecSort (pstate=0x563768e10898) at nodeSort.c:108
#25 0x0000563768228ee9 in ExecProcNode (node=0x563768e10898) at ../../../src/include/executor/executor.h:257
#26 gather_merge_readnext (gm_state=gm_state@entry=0x563768e06c78, reader=reader@entry=0, nowait=nowait@entry=true) at nodeGatherMerge.c:656
#27 0x0000563768229205 in gather_merge_init (gm_state=0x563768e06c78) at nodeGatherMerge.c:490
#28 gather_merge_getnext (gm_state=0x563768e06c78) at nodeGatherMerge.c:558
#29 ExecGatherMerge (pstate=0x563768e06c78) at nodeGatherMerge.c:267
#30 0x000056376821f011 in ExecProcNode (node=0x563768e06c78) at ../../../src/include/executor/executor.h:257
#31 fetch_input_tuple (aggstate=aggstate@entry=0x563768e102d8) at nodeAgg.c:581
#32 0x0000563768221aa6 in agg_retrieve_direct (aggstate=0x563768e102d8) at nodeAgg.c:2364
#33 ExecAgg (pstate=0x563768e102d8) at nodeAgg.c:2179
#34 0x000056376823c868 in ExecProcNode (node=0x563768e102d8) at ../../../src/include/executor/executor.h:257
#35 ExecSort (pstate=0x563768e06a68) at nodeSort.c:108
#36 0x0000563768210092 in ExecProcNode (node=0x563768e06a68) at ../../../src/include/executor/executor.h:257
#37 ExecutePlan (execute_once=<optimized out>, dest=0x563768e2ef80, direction=<optimized out>, numberTuples=0, sendTuples=<optimized out>, operation=CMD_SELECT, use_parallel_mode=<optimized out>, planstate=0x563768e06a68, estate=0x563768e05068) at execMain.c:1551
#38 standard_ExecutorRun (queryDesc=0x563768e0df98, direction=<optimized out>, count=0, execute_once=<optimized out>) at execMain.c:361
#39 0x0000563768373d8c in PortalRunSelect (portal=0x563768d98fd8, forward=<optimized out>, count=0, dest=<optimized out>) at pquery.c:921
#40 0x00005637683750c5 in PortalRun (portal=portal@entry=0x563768d98fd8, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x563768e2ef80, altdest=altdest@entry=0x563768e2ef80, qc=0x7ffcf6a53c20) at pquery.c:765
#41 0x00005637683714e3 in exec_simple_query (query_string=0x563768d2bc38 "select\n\tp_brand,\n\tp_type,\n\tp_size,\n\tcount(distinct ps_suppkey) as supplier_cnt\nfrom\n\tpartsupp,\n\tpart\nwhere\n\tp_partkey = ps_partkey\n\tand p_brand <> 'Brand#43'\n\tand p_type not like 'PROMO POLISHED%'\n\tan"...) at postgres.c:1215
#42 0x00005637683733a1 in PostgresMain (argc=argc@entry=1, argv=argv@entry=0x7ffcf6a54170, dbname=<optimized out>, username=<optimized out>) at postgres.c:4506
#43 0x00005637682f8581 in BackendRun (port=<optimized out>, port=<optimized out>) at postmaster.c:4530
#44 BackendStartup (port=<optimized out>) at postmaster.c:4252
#45 ServerLoop () at postmaster.c:1745
#46 0x00005637682f93bf in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x563768d25e00) at postmaster.c:1417
#47 0x00005637680989cd in main (argc=3, argv=0x563768d25e00) at main.c:249
```

## Environment
Staging

## Logs, links
- https://neondb.slack.com/archives/C033RQ5SPDH/p1671537500738639
- https://neondb.slack.com/archives/C039YKBRZB4/p1671538220179539
- https://neonprod.grafana.net/d/IJSLHBOnk/neon-logs-compute-nodes?orgId=1&var-datasource=grafanacloud-neonstaging-logs&var-project=compute-node-ep-silent-tooth-628729&var-search=&var-exclude=substing%20to%20exclude&var-region=us-east-2&from=1671734200000&to=1671734205000

### PR DESCRIPTION
**Pull request by MMeent**
If we ran `compact_prefetch_buffers` with exactly one hole in the buffers, the code would fail to remove the last, now unused, entry from the array.

This is now fixed. 

Also, add and adjust some comments in the compaction code so that the algorithm used is a bit more clear.

Fixes #3192

### CODE REVIEW

File: pgxn/neon/pagestore_smgr.c [hunk 1]
```diff
@@ -332,16 +335,22 @@ compact_prefetch_buffers(void)
...
+		/* update bookkeeping */
 		n_moved++;
 	}
 
-	if (MyPState->ring_last != empty_ring_index)
+	/*
+	 * Only when we've moved slots we can expect trailing unused slots,
+	 * so only then we clean up trailing unused slots.
+	 */
+	if (n_moved > 0)
```
Comment (knizhnik) [inline pgxn/neon/pagestore_smgr.c:353]: Right now it is assumed that if `compact_prefetch_buffers` returns false than current slot is used.
But it is not quite clear to me how it is enforced with this fix.
There are two loos `while (search_ring_index > MyPState->ring_last)` in  `compact_prefetch_buffers` 
First one is finished if it locates unused slot.
As far as it decrements `search_ring_index` second loop can be executed 0 times. In this case `n_moved` will be zero a and  `compact_prefetch_buffers` returns false. But is their any warranty that slow pointed `MyPState->ring_last` is used?

**Review by knizhnik — APPROVED** [review]

**Comment by vadim2404** [comment]
@MMeent, will you merge this PR?
