### PR TITLE
Fixes for enabling --timelines-onto-safekeepers in tests

### LINKED ISSUE #11424: make neon_local manage storcon sk registrations
PR #11261 has added code to register safekeepers to the storcon from NeonEnv, and PR #11419 has slightly modified that code.

However, we would ideally like to do this from `neon_local`, ideally via a config setting to make the storcon manage safekeepers as well as timelines.

part of #11670

### PR DESCRIPTION
**Pull request by arpad-m**
Second PR with fixes extracted from #11712, relating to `--timelines-onto-safekeepers`. Does the following:

* Moves safekeeper registration to `neon_local` instead of the test fixtures
* Pass safekeeper JWT token if `--timelines-onto-safekeepers` is enabled
* Allow some warnings related to offline safekeepers (similarly to how we allow them for offline pageservers)
* Enable generations on the compute's config if `--timelines-onto-safekeepers` is enabled
* fix parallel `pull_timeline` race condition (the one that #11786 put for later)

Fixes #11424
Part of #11670

### CODE REVIEW

File: control_plane/src/storage_controller.rs [hunk 1]
```diff
@@ -785,10 +816,31 @@ impl StorageController {
...
-        Ok(response
-            .json()
-            .await
-            .map_err(pageserver_client::mgmt_api::Error::ReceiveBody)?)
+        Ok(response)
+    }
+
+    /// Register the safekeepers in the storage controller
+    #[instrument(skip(self))]
+    async fn register_safekeepers(&self) -> anyhow::Result<()> {
```
Comment (DimasKovas) [inline control_plane/src/storage_controller.rs:824]: Don't we want safekeeper to register themselves?

File: safekeeper/src/pull_timeline.rs [hunk 2]
```diff
@@ -465,14 +465,27 @@ pub async fn handle_request(
...
         safekeeper_host,
         sk_auth_token,
         http_client,
         global_timelines,
     )
     .await
+    {
+        Ok(resp) => Ok(resp),
+        Err(e) => {
+            if let Some(TimelineError::AlreadyExists(_) | TimelineError::CreationInProgress(_)) =
```
Comment (DimasKovas) [inline safekeeper/src/pull_timeline.rs:479]: `CreationInProgress` does not guarantee that the parallel creation will succeed, so returning `200 OK` is not ok for it

Comment (arpad-m) [reply safekeeper/src/pull_timeline.rs:479]: Fair point. We could return `202 Accepted`, or `409 Conflict`. What do you think? I'm leaning towards latter.

File: control_plane/src/storage_controller.rs (hunk 1 above)
Comment (arpad-m) [reply control_plane/src/storage_controller.rs:824]: We already have the list here, it doesn't really matter imo.

File: safekeeper/src/pull_timeline.rs (hunk 2 above)
Comment (DimasKovas) [reply safekeeper/src/pull_timeline.rs:479]: Yeah, 409 looks better to me too

Comment (arpad-m) [reply safekeeper/src/pull_timeline.rs]: Done

**Review by DimasKovas — APPROVED** [review]
