### PR TITLE
Set heartbeat interval for chaos test

### LINKED ISSUE #10250: test_timeline_archival_chaos fails `len(timelines_deleted) > 10` assertion
[Lots of CI runs](https://neonprod.grafana.net/d/fddp4rvg7k2dcf/regression-test-failures?orgId=1&var-test_name=test_timeline_archival_chaos&from=now-7d&to=now&timezone=utc&var-restrict=true&var-max_count=100&var-reference=$__all&var-ignore_reference=refs%2Fpull%2F0000%2Fmerge) with unrelated changes are failing on this assertion:

https://github.com/neondatabase/neon/blob/28ccda0a63f9661d961dbb1e5372f4a78d80346d/test_runner/regress/test_timeline_archive.py#L651-L653

### PR DESCRIPTION
**Pull request by knizhnik**
## Problem

See https://neondb.slack.com/archives/C033RQ5SPDH/p1734707873215729

test_timeline_archival_chaos becomes more flaky with increased heartbeat interval

Resolves #10250.

## Summary of changes

Override heatbeat interval for `test_timelirn_archival_chaos.py`

### CODE REVIEW

File: pageserver/client/src/page_service.rs [hunk 1]
```diff
@@ -60,7 +60,7 @@ impl Client {
     ) -> anyhow::Result<PagestreamClient> {
         let copy_both: tokio_postgres::CopyBothDuplex<bytes::Bytes> = self
             .client
-            .copy_both_simple(&format!("pagestream_v2 {tenant_id} {timeline_id}"))
+            .copy_both_simple(&format!("pagestream_v3 {tenant_id} {timeline_id}"))
```
Comment (ololobus) [inline pageserver/client/src/page_service.rs:63]: Looks like you pushed a lot of unrelated changes related to the protocol change

Comment (knizhnik) [reply pageserver/client/src/page_service.rs]: Sorry, fixed

**Review by ololobus — APPROVED** [review]
LGTM, unless @jcsp has any objections

**Review by jcsp — APPROVED** [review]
