### PR TITLE
scrubber: retry when missing index key in the listing

### LINKED ISSUE #8872: scrubber: handle race between timeline deletion and `list_timeline_blobs`
## Description

In https://github.com/neondatabase/neon/pull/8344 we argued that there would not be a race between object deletion and scrubber metadata health checks:

> This case is made impossible by always read the tenant objects listing first before downloading the index.

However, it is possible that the reading the listing itself races with timeline deletion.

### Scenario 1

RemoteTimelineClient | Scrubber |
| -- | -- |
|  | `list_timeline_blobs` begin | 
|  | read listing `A` | 
| delete `A` | |
| delete `index_part` | |
| | `list_timeline_blobs` end | |

In this case, scrubber will report a false positive that `parse error: S3 list response got no index_part.json file`, but this is not a metadata corruption since we are deleting the timeline.

### Scenario 2

RemoteTimelineClient | Scrubber |
| -- | -- |
|  | `list_timeline_blobs` begin | 
|  | read listing `index_part` | 
|  | read listing `A` | 
| delete `A` | |
| delete `index_part` | |
| | `download_object_with_retries(<index_part path>)` | |

In this case, when we try to download the latest index, we will get an error saying `Failed to download object for key <path to index>: No file found for the remote object id given`.

## DoD

- Eliminate or resolve this race between scrubber scan and remote timeline client.

### PR DESCRIPTION
**Pull request by yliang412**
Part of #8128, fixes #8872.

## Problem

See #8872.

## Summary of changes

- Retry `list_timeline_blobs` another time if 
  - there are layer file keys listed but not index.
  - failed to download index.
- Instrument code with `analyze-tenant` and `analyze-timeline` span.
- Remove `initdb_archive` check, it could have been deleted.
- Return with exit code 1 on fatal error if `--exit-code` parameter is set.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

File: storage_scrubber/src/checks.rs [hunk 1]
```diff
@@ -366,30 +408,28 @@ pub(crate) async fn list_timeline_blobs(
...
             None => {
-                tracing::warn!("Unknown key {key}");
-                errors.push(format!("S3 list response got an object with odd key {key}"));
+                tracing::info!("S3 listed an unknown key: {key}");
                 unknown_keys.push(obj);
             }
         }
     }
 
-    if index_part_keys.is_empty() && s3_layers.is_empty() && initdb_archive {
```
Comment (yliang412) [inline storage_scrubber/src/checks.rs:384]: This is actually the place I think caused the "Fatal scrub errors detected" may come from in preprod.

Comment (yliang412) [reply storage_scrubber/src/checks.rs:384]: cc: @skyzh `initdb_archive` could have been false in this case, but I did handle the race between list_object and delete_object by retrying.

**Comment by skyzh** [comment]
For anything that may interrupts user operation and requires manual fix, it should be a fatal error. Otherwise it should be a warning, and we can periodically check for these warnings and see how to resolve them.

**Comment by yliang412** [comment]
> okay I just realized that I might created a quick fix that might be part of this PR will address #9068, should I close my PR?

It might still be good to have it though.

File: storage_scrubber/src/checks.rs [hunk 2]
```diff
@@ -377,11 +376,54 @@ pub(crate) fn parse_layer_object_name(name: &str) -> Result<(LayerName, Generati
...
+/// To avoid generating false positive, we try streaming the listing for a second time.
 pub(crate) async fn list_timeline_blobs(
     remote_client: &GenericRemoteStorage,
     id: TenantShardTimelineId,
     root_target: &RootTarget,
 ) -> anyhow::Result<RemoteTimelineBlobData> {
+    let res = list_timeline_blobs_impl(remote_client, id, root_target).await?;
+    match res {
+        ListTimelineBlobsResult::Ready(data) => Ok(data),
+        ListTimelineBlobsResult::MissingIndexPart(_) => {
```
Comment (skyzh) [inline storage_scrubber/src/checks.rs:393]: I don't think it's in general a good idea to simply do such meta operation twice. Would be better if we skip the tenants with missing index inside `list_timeline_blobs`? (As in my PR)

File: storage_scrubber/src/scan_pageserver_metadata.rs [hunk 3]
```diff
@@ -169,45 +170,54 @@ pub async fn scan_pageserver_metadata(
...
+                    timeline_ids.insert(ttid.timeline_id);
+                } else {
+                    tracing::info!(
+                        "Skip analysis of {} b/c a lower shard count than {}",
+                        ttid,
+                        highest_shard_count.0,
+                    );
+                }
             }
+            .instrument(
```
Comment (skyzh) [inline storage_scrubber/src/scan_pageserver_metadata.rs:217]: if you don't specify the parent it will automatically inherit the current one?

File: storage_scrubber/src/scan_pageserver_metadata.rs [hunk 4]
```diff
@@ -306,15 +317,18 @@ pub async fn scan_pageserver_metadata(
...
         analyze_tenant(
             &remote_client,
-            tenant_id.expect("Must be set if results are present"),
+            tenant_id,
             &mut summary,
             tenant_objects,
             tenant_timeline_results,
             highest_shard_count,
         )
+        .instrument(info_span!("", tenant = %tenant_id))
```
Comment (skyzh) [inline storage_scrubber/src/scan_pageserver_metadata.rs:331]: should assign each of the span a name

**Review by skyzh — COMMENTED** [review]
rest LGTM

File: storage_scrubber/src/checks.rs (hunk 2 above)
Comment (yliang412) [reply storage_scrubber/src/checks.rs:393]: Yes, but this could become a false positive and trigger the alert? On the other hand, if we choose to not add this as a fatal error, we could also miss some serious problem.

Comment (skyzh) [reply storage_scrubber/src/checks.rs:393]: well, at a second thought, it makes some sense to retry twice here to handle deleted branches...

Comment (yliang412) [reply storage_scrubber/src/checks.rs:393]: Sounds good, I will still incorporate your PR: we will add it as a timeline check error if it failed the download the second time.

Comment (yliang412) [reply storage_scrubber/src/checks.rs:393]: Incoporated #9068: daf22c39ad2c7051e6a51af9fc741eba8a1c03cd

File: storage_scrubber/src/scan_pageserver_metadata.rs (hunk 4 above)
Comment (yliang412) [reply storage_scrubber/src/scan_pageserver_metadata.rs]: added a name to both spans: bb1de166adfa49f8f1d495496486d6bcbde51103

File: storage_scrubber/src/scan_pageserver_metadata.rs (hunk 3 above)
Comment (skyzh) [reply storage_scrubber/src/scan_pageserver_metadata.rs:217]: well, I feel this is fine as it resembles more the best practice (probably?) of the tracing spans...

File: storage_scrubber/src/main.rs [hunk 5]
```diff
@@ -380,6 +380,7 @@ pub async fn scan_pageserver_metadata_cmd(
 
             if summary.is_fatal() {
                 tracing::error!("Fatal scrub errors detected");
+                std::process::exit(1);
```
Comment (skyzh) [inline storage_scrubber/src/main.rs:383]: can we make it a command line parameter? (i.e., `scrubber --exit-code` returns 1 when there's fatal error, and without the parameter, it returns 0.

I saw there are "fatal errors" across all regions and I don't want the alerts to fire now. Once we resolved all the fatal errors, I'll add such parameters to the infra repo and the alert will start to fire.

**Review by skyzh — APPROVED** [review]
Rest LGTM, good work :)

File: storage_scrubber/src/main.rs (hunk 5 above)
Comment (yliang412) [reply storage_scrubber/src/main.rs]: Yes, added in f4e9a797ebe81f297beac9aacea2d15b61153f4b. and I think once we resolve all the fatal errors, it will make more sense to post scrub results to storcon (with `--post`).
