### PR TITLE
fix(layer): remove the need to repair internal state

### LINKED ISSUE #6028: layer: evict downloaded-but-not-initialized
This issue is a catch-all for `struct Layer` situations where the internal state (`LayerInner::inner`) does not match filesystem (file present, not present).

"downloaded-but-not-initialized" happens when a call to `LayerInner::get_or_maybe_download` changes state such that an eviction is cancelled, but the call is cancelled before it reinitializes or downloads and initializes the internal state. Currently the workaround is to have `Layer::keep_resident` be async, to do initialization (repair) but not download.

As recently noticed, the `Layer::keep_resident` will need to wait for an ongoing download. This can mean 10min wait during an overloaded situation. Slow `Layer::keep_resident` slows down collecting resident layers (`LayerManager::resident_layers`) called from most importantly disk usage based eviction. This need to wait for a download is very much against original design goals, which only succeeded for `Layer::evict_and_wait`.

### Keep only the fastest path spawn-less

Currently only downloading the layer involves spawning a new task. A spawn would make the make the "file is present locally" case initialization cancellation safe. Spawning however is difficult due to `heavier_once_cell::OnceCell` using a `std::sync::Mutex` internally, but also because we would have to do the `stat` call while holding the mutex.

Alternative to doing `stat` while holding the mutex is to have the `spawn_blocking`'d eviction wait for the semaphore with `Handle::block_on`, exposing it to wait on a download. The `Handle::block_on` wait on semaphore permit could be short-circuited by signalling when we've decided to download and not just reinitialize.

### Additional state to track the last known filesystem status

During timeline layermap initialization, we know if the layer is evicted or present. When new layers are created locally, we know they are present because a blocking `std::fs::rename` from the temporary path succeeds. Seems obvious we could cache this knowledge, only later updated when eviction's `std::fs::remove_file` succeeds.

Caching the value will expose another problem I was hoping to avoid originally. If we end up in a state where a previous `spawn_blocking` eviction was "cancelled", we should fire up a new one from `Layer::evict_and_wait`. In the meantime the `Layer::keep_resident` should report status based on this cached value.

### Race `Layer::keep_resident` to when download path is entered

Would a `watch` channel change the size of the `Layer`?

---

"downloaded-but-not-initialized" happens if there is a single cancelled request which ends up firing up the download, which is not cancellation safe. Could make it, or could make evictions work even if we don't know if we are initialized or not. Filesystem is the ground truth for this.

_Originally posted by @koivunej in https://github.com/neondatabase/neon/pull/6000#discussion_r1413890430_

### LINKED ISSUE #7145: Layer::keep_resident will wait for layer download blocking disk usage based eviction
This is an issue for the 10-minute hang on #5331 first observed in staging. It is related to #6028, which tracks the need for `Layer::keep_resident` to repair the state.

A fix is in #7030 -- use a separate watch channel to signal intent to begin a download, thus canceling the semaphore wait that a later started `Layer::keep_resident` would be doing.

The need to wait for downloads caused a disk full situation on 2024-03-15 00:32:00 on `pageserver-0.eu-west-1.aws.neon.build` because a download was awaited, which could not be completed. After all, the disk was full, and we currently do not preallocate space for downloads, so it always failed, not in the beginning, but somewhere along the way. A failed download, such as disk full or not found[^1], will also cause `Layer::keep_resident` to wait for exponential backoff.

[^1]: In past staging issues when generation numbers have rolled back, there had been retrying on S3 returning "not found". It should no longer be retried after (PR, which moved timeouts to remote_storage).

### PR DESCRIPTION
**Pull request by koivunej**
## Problem

The current implementation of struct Layer supports canceled read requests, but those will leave the internal state such that a following `Layer::keep_resident` call will need to repair the state. In pathological cases seen during generation numbers resetting in staging or with too many in-progress on-demand downloads, this repair activity will need to wait for the download to complete, which stalls disk usage-based eviction. Similar stalls have been observed in staging near disk-full situations, where downloads failed because the disk was full.

Fixes #6028 or the "layer is present on filesystem but not evictable" problems by:
1. not canceling pending evictions by a canceled `LayerInner::get_or_maybe_download`
2. completing post-download initialization of the `LayerInner::inner` from the download task

Not canceling evictions above case (1) and always initializing (2) lead to plain `LayerInner::inner` always having the up-to-date information, which leads to the old `Layer::keep_resident` never having to wait for downloads to complete. Finally, the `Layer::keep_resident` is replaced with `Layer::is_likely_resident`. These fix #7145.

## Summary of changes

- add a new test showing that a canceled get_or_maybe_download should not cancel the eviction
- switch to using a `watch` internally rather than a `broadcast` to avoid hanging eviction while a download is ongoing
- doc changes for new semantics and cleanup
- fix `Layer::keep_resident` to use just `self.0.inner.get()` as truth as `Layer::is_likely_resident`
- remove `LayerInner::wanted_evicted` boolean as no longer needed

Builds upon: #7185. Cc: #5331.

### CODE REVIEW

File: pageserver/src/tenant/storage_layer/layer/failpoints.rs [hunk 1]
```diff
@@ -0,0 +1,90 @@
+use super::*;
+
+impl LayerInner {
+    #[cfg(test)]
```
Comment (koivunej) [inline pageserver/src/tenant/storage_layer/layer/failpoints.rs:4]: The module is `#[cfg(test)]`, no need for this.

**Comment by koivunej** [comment]
Rebased away the conflict, handled the `#[cfg(test)]` mess in failpoints.

File: pageserver/src/tenant/storage_layer/layer/tests.rs [hunk 2]
```diff
@@ -241,131 +241,311 @@ async fn evict_and_wait_on_wanted_deleted() {
...
+        let (arrival, arrived_at_barrier) = utils::completion::channel();
+        layer.enable_failpoint(failpoints::Failpoint::WaitBeforeStartingEvicting(
+            Some(arrival),
+            barrier,
+        ));
+
+        // now the eviction cannot proceed because the threads are consumed while completion exists
+        drop(resident);
+
+        // synchronize so we don't have two different possible outcomes for this test
```
Comment (koivunej) [inline pageserver/src/tenant/storage_layer/layer/tests.rs:301]: Outdated comment.

File: pageserver/src/tenant/storage_layer/layer.rs [hunk 3]
```diff
@@ -1234,6 +1234,9 @@ impl LayerInner {
             // first we spawn off the async part, then it will spawn_blocking the blocking part
             Self::spawn(start_evicting.instrument(span));
         }
+
+        // if can_evict is now false, we must cancel the eviction but get_or_maybe_download has
+        // already done that.
```
Comment (koivunej) [inline pageserver/src/tenant/storage_layer/layer.rs:1239]: Not sure about this after all. It would be sensible to remove the whole wanted_evicted instead.

Comment (koivunej) [reply pageserver/src/tenant/storage_layer/layer.rs]: Decided to remove `wanted_evicted: AtomicBool` altogether instead of worrying about this more: https://github.com/neondatabase/neon/pull/7030/commits/6c062d9edad001ec5f51c542de868677fdaf0bd0

File: pageserver/src/tenant/storage_layer/layer/tests.rs (hunk 2 above)
Comment (koivunej) [reply pageserver/src/tenant/storage_layer/layer/tests.rs:301]: [befd60e](https://github.com/neondatabase/neon/pull/7030/commits/befd60e766904ddc94ca252e4e3b63dbed602a19)

**Review by problame — APPROVED** [review]
