### PR TITLE
Fix rustdoc warnings and test cargo doc in CI

### LINKED ISSUE #2557: Run `rustdoc --check` in CI to prevent broken intra-doc links
I recently discovered that `rustdoc` has a `--check` flag to avoid generating documentation, and just produce warnings/errors. We currently have a number of broken internal doc links, so (after fixing them) it'd be great to automatically prevent more from being added.

### Problems

Overall, running this right now might be a bit hacky:

* There's no `cargo doc --check` command (see: https://github.com/rust-lang/cargo/issues/10025, https://github.com/rust-lang/cargo/pull/8859)
* `rustdoc --check` requires nightly (see: https://github.com/rust-lang/rust/pull/78984)
* `cargo rustdoc ...` can only be run for one crate at a time (not too bad; we can just loop through all of them)

### Sample command

Currently, the following correctly runs, but requires nightly:

```
cargo +nightly rustdoc -p pageserver --lib -- -Z unstable-options --check
```

Notes:

* `-Z unstable-options` is required for `--check`.
* `-p pageserver` is required because `rustdoc` expects only a single crate
* `--lib` is required because `pageserver` has both `lib` and `bin` targets, and `rustdoc` needs just one
* (not shown) We have to also have to either pass `--deny rustdoc::all` or `--deny rustdoc::$lint` (for each lint) in order to cause rustdoc to exit with a non-zero status code

In general, requiring an extra nightly version in CI might be too much. It's "just" checking the code for dependencies + target crate, so not nearly as much as a full compilation -- it takes ~1.4 minutes on my machine (8 core/16 thread) to run the command above. It's then ~1 second for running on an additional crate (e.g., `safekeeper`).

In terms of possible nightly issues: I think we can mostly avoid stability issues by pinning to a particular version. We're also not compiling anything, so there's a lot of potential instability avoided there as well. It also _might_ be possible to do something extraordinarily hacky and use nightly features with our stable tools (e.g, as in https://fasterthanli.me/articles/why-is-my-rust-build-so-slow#how-much-time-are-we-spending-on-these-steps). The really hacky version looks like:

```
RUSTC_BOOTSTRAP=1 cargo rustdoc -p pageserver --lib -- -Z unstable-options --check
```

It performs an initial run much faster (17.5s).

### PR DESCRIPTION
**Pull request by arpad-m**
## Problem

`cargo +nightly doc` is giving a lot of warnings: broken links, naked URLs, etc.

## Summary of changes

* update the `proc-macro2` dependency so that it can compile on latest Rust nightly, see https://github.com/dtolnay/proc-macro2/pull/391 and https://github.com/dtolnay/proc-macro2/issues/398
* allow the `private_intra_doc_links` lint, as linking to something that's private is always more useful than just mentioning it without a link: if the link breaks in the future, at least there is a warning due to that. Also, one might enable [`--document-private-items`](https://doc.rust-lang.org/cargo/commands/cargo-doc.html#documentation-options) in the future and make these links work in general.
* fix all the remaining warnings given by `cargo +nightly doc`
* make it possible to run `cargo doc` on stable Rust by updating `opentelemetry` and associated crates to version 0.19, pulling in a fix that previously broke `cargo doc` on stable: https://github.com/open-telemetry/opentelemetry-rust/pull/904
* Add `cargo doc` to CI to ensure that it won't get broken in the future. 

Fixes #2557

## Future work
* Potentially, it might make sense, for development purposes, to publish the generated rustdocs somewhere, like for example [how the rust compiler does it](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_driver/index.html). I will file an issue for discussion.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Comment by vadim2404** [comment]
Should we incorporate this check into CI?

File: libs/pageserver_api/src/models.rs [hunk 1]
```diff
@@ -411,12 +411,16 @@ pub struct LayerResidenceEvent {
...
+/// The reason for recording a given [`LayerResidenceEvent`].
 #[derive(Debug, Clone, Copy, Serialize, Deserialize)]
 pub enum LayerResidenceEventReason {
     /// The layer map is being populated, e.g. during timeline load or attach.
     /// This includes [`RemoteLayer`] objects created in [`reconcile_with_remote`].
     /// We need to record such events because there is no persistent storage for the events.
+    ///
+    // https://github.com/rust-lang/rust/issues/74481
+    /// [`RemoteLayer`]: ../pageserver/tenant/storage_layer/struct.RemoteLayer.html
+    /// [`reconcile_with_remote`]: ../pageserver/tenant/struct.Timeline.html#method.reconcile_with_remote
```
Comment (koivunej) [inline libs/pageserver_api/src/models.rs:423]: Is the rust issue meant to be linekd here?

**Review by koivunej — APPROVED** [review]
I think these are good changes.

**Comment by vadim2404** [comment]
related to #2557

File: libs/pageserver_api/src/models.rs (hunk 1 above)
Comment (arpad-m) [reply libs/pageserver_api/src/models.rs:423]: The rust issue is just that we have to link to the html because intra doc links don't support linking to dependents.

But the links actually don't work, I need to fix them, thanks for bringing this up.

**Comment by arpad-m** [comment]
> Should we incorporate this check into CI?

I think so. Originally this PR didn't have such a CI check as nightly was required to run `cargo doc` and CI currently only has one stable Rust version. But then I changed the PR to update `opentelemetry` to 0.19 to fix the stable `cargo doc` build, so I've now added it to CI.

**Comment by arpad-m** [comment]
Okay, a trial edit to add a broken link to the code [is showing a failure as expected](https://github.com/neondatabase/neon/actions/runs/5549304618/jobs/10133245878?pr=4711), very nice. I've removed that edit from the CI now.

**Review by koivunej — APPROVED** [review]
Still looking good.

I don't think we have any tests for the otel stuff, the parts that we use. They don't publish a clear changelog so ... aah they have per crate changelog:

- http 0.7 -> 0.8, looks quite boring
- otlp 0.11 -> 0.12, similarly boring, deps (within and outside otel)
- reqwest-tracing bump, for otel
- otel semantic conventions, deps
- proc_macro2 was for latest nightlies I understood?

I think these are all looking very mundane version bumps, and thus we could merge this even today but perhaps it's best to still consider if we release and what we release. So let's hold merging until that has been clarified.

File: .github/workflows/build_and_test.yml [hunk 2]
```diff
@@ -127,6 +127,11 @@ jobs:
       - name: Run cargo clippy (release)
         run: cargo hack --feature-powerset clippy --release $CLIPPY_COMMON_ARGS
 
+      - name: Check documentation generation
+        run: cargo doc --all
```
Comment (koivunej) [inline .github/workflows/build_and_test.yml:131]: Bubbling these up from DM's:

- `--all` => `--workspace` (as I am always confused by `--all` -- though, since we have top level crate without code it probably defaults to that)
- how about `--no-deps`?
- does `--document-private-items` here affect any lints or will we get the same regardless?

Comment (koivunej) [reply .github/workflows/build_and_test.yml:131]:
```suggestion
        run: cargo doc --workspace
```

Comment (arpad-m) [reply .github/workflows/build_and_test.yml:131]: >     * how about `--no-deps`? While this PR does upgrade some deps to get them to be `cargo doc`'d I've just always used `--no-deps` for the less walltime spent; is there nowdays some loss of functionality I am not aware of (assuming we'll publish these in future)?

Good point

>     * would a `--document-private-items` here affect any lints or will we get the same regardless?

I think there won't be any change. I think it's cleaner to pass that instead of passing `-Arustdoc::private_intra_doc_links`.

Comment (koivunej) [reply .github/workflows/build_and_test.yml]: Should we add a `--document-private-items` to this cmdline?

Comment (arpad-m) [reply .github/workflows/build_and_test.yml]: I've added it.
