### PR TITLE
Fix tenant config parsing. Add a test

### LINKED ISSUE #1580: Restarting ps throws tenant config error
Can't shutdown and restart PS. Tenant and branch were all created on a fresh db,
 
```
2022-04-26T15:26:27.182754Z  INFO Got SIGQUIT. Terminating in immediate shutdown mode
2022-04-26T15:29:09.619815Z  INFO version: git:d796622a25783de945bfade155a3810f4778f6c8-modified
2022-04-26T15:29:09.619902Z  INFO Starting pageserver http handler on localhost:15001
2022-04-26T15:29:09.620376Z  INFO Starting pageserver pg protocol handler on localhost:15000
2022-04-26T15:29:09.620511Z  INFO daemonizing...
2022-04-26T15:29:09.621486Z  INFO Success, daemonized
2022-04-26T15:29:09.623462Z  INFO No remote storage configured, skipping storage sync, considering all local timelines with correct metadata files enabled
2022-04-26T15:29:09.623715Z  INFO load tenantconf from /home/d/src/github.com/zenithdb/zenith/test_output/test_ancestor_branch/repo/tenants/99ab701fa31e4f7b9cc32f4ec755c466/config
Error: Failed to start pageserver

Caused by:
    0: Failed to load repo for tenant 99ab701fa31e4f7b9cc32f4ec755c466
    1: unrecognized pageserver option 'checkpoint_distance'

```

Tenant config,
```
# [tenant_config]
checkpoint_distance = 4194304
compaction_target_size = 4194304
compaction_period = { secs = 600, nanos = 0 }
compaction_threshold = 2
gc_horizon = 1048576
gc_period = { secs = 600, nanos = 0 }
```

### PR DESCRIPTION
**Pull request by lubennikovaav**
fix #1580
 
With this new test, I also found a bug in Duration options serialization. Fixed in this PR.

### CODE REVIEW

File: pageserver/src/layered_repository.rs [hunk 1]
```diff
@@ -712,13 +712,15 @@ impl LayeredRepository {
...
 
-# [tenant_config]
+[tenant_config]
 "#
         .to_string();
 
         // Convert the config to a toml file.
         conf_content += &toml_edit::easy::to_string(&tenant_conf)?;
 
+        info!("conf_content {}", conf_content);
```
Comment (dhammika) [inline pageserver/src/layered_repository.rs:722]: Not sure if this a good idea. If we add any sensitive data ie. tokens/keys to tenant conf they'll get logged too. May be make it a debug.

**Review by dhammika — APPROVED** [review]
:+1:

File: pageserver/src/layered_repository.rs (hunk 1 above)
Comment (LizardWizzard) [reply pageserver/src/layered_repository.rs]: We have an example of that in proxy code, if needed we can make a custom display that omits sensitive fields
