### PR TITLE
fix(pageserver): update the `STORAGE_IO_TIME` metrics to avoid expensive operations

### LINKED ISSUE #5131: `STORAGE_IO_TIME`: don't use `with_label_values` on the hot path
Every VirtualFile::read, we waste time hashing the `op="read"` label here, plus locking and mutex overhead.

Do it like StorageTimeMetrics instead.

### PR DESCRIPTION
**Pull request by duguorong009**
Introduce the `StorageIoOperation` enum, `StorageIoTime` struct, and `STORAGE_IO_TIME_METRIC` static which provides lockless access to histograms consumed by `VirtualFile`.

Closes #5131

### CODE REVIEW

File: pageserver/src/metrics.rs [hunk 1]
```diff
@@ -548,7 +548,52 @@ const STORAGE_IO_TIME_BUCKETS: &[f64] = &[
...
+    Close,
+    CloseByReplace,
+    Read,
+    Write,
+    Seek,
+    Fsync,
+    Metadata,
+}
+
+impl StorageIoOperation {
```
Comment (knizhnik) [inline pageserver/src/metrics.rs:565]: Why not to use use `strum_macros::EnumString` ?

**Review by knizhnik — APPROVED** [review]

File: pageserver/src/metrics.rs (hunk 1 above)
Comment (duguorong009) [reply pageserver/src/metrics.rs:565]: Um, afaik, this [CloseByReplace](https://github.com/duguorong009/neon/blob/gr/storage-io-time-metrics-improval/pageserver/src/metrics.rs#L570C70-L570C70) cannot be directly built from `string`.
That's why I added the manual impls.

**Comment by duguorong009** [comment]
BTW, @knizhnik 
Can you revoke the PR approval?
This PR is still draft, and needs more commits for completion.

File: pageserver/src/metrics.rs [hunk 2]
```diff
@@ -558,6 +588,30 @@ pub(crate) static STORAGE_IO_TIME: Lazy<HistogramVec> = Lazy::new(|| {
...
+        });
+        Self { metrics }
+    }
+
+    pub(crate) fn get(&self, op: StorageIoOperation) -> Histogram {
+        self.metrics[op as usize]
+    }
+}
+
+pub(crate) const STORAGE_IO_TIME_METRIC: StorageIoTime = StorageIoTime::new();
```
Comment (koivunej) [inline pageserver/src/metrics.rs:613]:
```suggestion
pub(crate) static STORAGE_IO_TIME_METRIC: Lazy<StorageIoTime> = Lazy::new(|| StorageIoTime::new());
```

Then this should work just fine.

StorageIoTime cannot be const because STORAGE_IO_TIME is not const. `static` is good here.

File: pageserver/src/metrics.rs [hunk 3]
```diff
@@ -558,6 +588,30 @@ pub(crate) static STORAGE_IO_TIME: Lazy<HistogramVec> = Lazy::new(|| {
     .expect("failed to define a metric")
 });
 
+#[derive(Debug)]
+struct StorageIoTime {
+    metrics: [Histogram; StorageIoOperation::COUNT],
+}
+
+impl StorageIoTime {
+    fn new() -> Self {
```
Comment (koivunej) [inline pageserver/src/metrics.rs:597]: Now the `STORAGE_IO_TIME` could be moved within this `fn new` because it should not be accessed from elsewhere, right? Probably does not need any `static` or `Lazy` either.

Comment (duguorong009) [reply pageserver/src/metrics.rs:597]: yes, right. @koivunej

File: pageserver/src/metrics.rs [hunk 4]
```diff
@@ -548,7 +548,37 @@ const STORAGE_IO_TIME_BUCKETS: &[f64] = &[
...
+}
+
+impl StorageIoOperation {
+    pub fn as_str(&self) -> &'static str {
+        match self {
+            StorageIoOperation::Open => "open",
+            StorageIoOperation::Close => "close",
+            StorageIoOperation::CloseByReplace => "close-by-replace",
+            StorageIoOperation::Read => "read",
+            StorageIoOperation::Write => "write",
```
[the remark this answers is not in the document]
Comment (duguorong009) [reply pageserver/src/metrics.rs:572]: Um, I didn't see any `read_at` or `write_at`.
I just copy/paste the raw strings here.
So, I am sure original ones are `read` and `write`.(Ex: https://github.com/neondatabase/neon/pull/5273/files#diff-840e039538d6fae00a64dd5896f48c3132fbf7d3f82c84fd1aed3f76ee62fd6aL526)

File: pageserver/src/metrics.rs [hunk 5]
```diff
@@ -548,15 +548,66 @@ const STORAGE_IO_TIME_BUCKETS: &[f64] = &[
...
-pub(crate) static STORAGE_IO_TIME: Lazy<HistogramVec> = Lazy::new(|| {
-    register_histogram_vec!(
-        "pageserver_io_operations_seconds",
-        "Time spent in IO operations",
-        &["operation"],
-        STORAGE_IO_TIME_BUCKETS.into()
-    )
-    .expect("failed to define a metric")
-});
+#[derive(
```
Comment (koivunej) [inline pageserver/src/metrics.rs:551]: I think we no longer need this comment listing which is confusing (me at least, in https://github.com/neondatabase/neon/pull/5273/files#r1321287671) -- it was added after some comment about "it'd be nice to have all of the variants" explained, but now we do have them, as proper enum variants.

File: pageserver/src/metrics.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (koivunej) [reply pageserver/src/metrics.rs:572]: Oki, I just ... misunderstood (likely my own) comment there above :)

I'll resolve this.

File: pageserver/src/metrics.rs (hunk 5 above)
Comment (koivunej) [reply pageserver/src/metrics.rs:551]: Or it could be moved to be per variant docs but ... These are quite self-explanatory, at except maybe `CloseByReplace`.

Comment (koivunej) [reply pageserver/src/metrics.rs:551]: Well, this is no biggie, we can handle it later.

**Review by koivunej — APPROVED** [review]

File: pageserver/src/metrics.rs [hunk 6]
```diff
@@ -548,15 +548,66 @@ const STORAGE_IO_TIME_BUCKETS: &[f64] = &[
...
+        });
+        Self { metrics }
+    }
+
+    pub(crate) fn get(&self, op: StorageIoOperation) -> &Histogram {
+        &self.metrics[op as usize]
+    }
+}
+
+pub(crate) static STORAGE_IO_TIME_METRIC: Lazy<StorageIoTime> = Lazy::new(|| StorageIoTime::new());
```
Comment (koivunej) [inline pageserver/src/metrics.rs:610]: Working around clippy:

```suggestion
pub(crate) static STORAGE_IO_TIME_METRIC: Lazy<StorageIoTime> = Lazy::new(StorageIoTime::new);
```

**Comment by duguorong009** [comment]
Thanks for the help! @koivunej 
BTW, it seems that the CI PR does not automatically fetch your commit. :man_shrugging:

**Comment by koivunej** [comment]
> Thanks for the help! @koivunej BTW, it seems that the CI PR does not automatically fetch your commit. 🤷‍♂️

Needed to consult for help, seems I needed to add the label again.
