### PR TITLE
Dump backtrace if a core dump is called just "core"

### LINKED ISSUE #2800: Capture and recovery of core dumps from regression tests
While looking at the first instances of #2780 it was noticed that we don't currently upload core dumps, or even create them on disk. Rationale is that we might end up having a rare crash during tests, but for a case like #2780 it might be really difficult to debug that rare crash if we don't have anything more than logs.

Implementation ideas:

- `ulimit -c unlimited`
- possibly reconfigure kernel's core dump facilities
- collect the dump files in [`def allure_attach_from_dir`](https://github.com/neondatabase/neon/blob/main/test_runner/fixtures/utils.py#L163-L191)

### PR DESCRIPTION
**Pull request by hlinnaka**
I hope this lets us capture backtraces in CI. At least it makes it work on my laptop, which is valuable even if we need to do more for CI.

Fixes #2800.

### CODE REVIEW

**Comment by hlinnaka** [comment]
If this works, a backtrace should appear in the compute log of the `test_endpoint_crash[debug-pg16-trigger_segfault]`.

File: compute_tools/src/compute.rs [hunk 1]
```diff
@@ -1134,8 +1137,17 @@ impl ComputeNode {
...
             let entry = entry.ok()?;
-            let _ = entry.file_name().to_str()?.strip_prefix("core.")?;
-            Some(entry.path())
+
+            let is_core_dump = match entry.file_name().to_str()? {
+                n if n.starts_with("core.") => true,
+                n if n == "core" => true,
+                _ => false,
+            };
+            if is_core_dump {
```
Comment (arpad-m) [inline compute_tools/src/compute.rs:1146]: This can also be expressed as `is_core_dump.then(|| entry.path())`

Comment (hlinnaka) [reply compute_tools/src/compute.rs:1146]: matter of taste but I find this more readable as an if-else, even though it's more verbose

**Comment by hlinnaka** [comment]
Ok, I now see a stacktrace in the compute log on x64 tests, e.g: https://neon-github-public-dev.s3.amazonaws.com/reports/pr-9125/11019165404/index.html#behaviors/b1a8273437954620fa374b796ffaacdd/449cc866dbb1dc47/?attachment=9d9a072d64577a52.

But not on arm64 test runs. I guess we have configured those runners differently?

In any case, this PR seems good to so, I'll merge.

**Review by bayandin — APPROVED** [review]
Wow, that's cool!

> But not on arm64 test runs. I guess we have configured those runners differently?

cc @cicdteam regarding runners setup

File: Dockerfile.build-tools [hunk 2]
```diff
@@ -13,6 +13,8 @@ RUN useradd -ms /bin/bash nonroot -b /home
 SHELL ["/bin/bash", "-c"]
 
 # System deps
+#
+# 'gdb' is includd so that we get backtraces of core dumps produced in regression tests
```
Comment (mattpodraza) [inline Dockerfile.build-tools:17]: Nit: a typo
```suggestion
# 'gdb' is included so that we get backtraces of core dumps produced in regression tests
```
