### PR TITLE
proxy: fix memory leak

### LINKED ISSUE #4672: proxy: memory leak
Summarizing discussion after #4612 @conradludgate noticed that Peak RSS grows up to gigabytes during the lifetime of proxy sessions. While our metrics are very coarse (no anon pages metric on proxies) it was noticed that in [`proxy_pass`](https://github.com/neondatabase/neon/blob/76b1cdc17e2e5f212f30de3515585ff78028678f/proxy/src/proxy.rs#L476) we never clear the metrics, contributing or causing the memory leak.

We use the collected metrics as part of billing, so we cannot immediatedly drop them, we need some grace period, or change how they are read as part of consumption metrics.

Slack thread: https://neondb.slack.com/archives/C04DGM6SMTM/p1688391989363929

### PR DESCRIPTION
**Pull request by conradludgate**
## Problem

these JoinSets live for the duration of the process. they might have many millions of connections spawned on them and they never get cleared.

Fixes #4672 

## Summary of changes

Drain the connections as we go

## Proof

Running proxy with 50000 connections over 100 seconds

### Before
Screenshot 2023-10-04 at 19 29 25
### After
Screenshot 2023-10-04 at 19 29 45

## Checklist before requesting a review

- [X] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

**Review by koivunej — APPROVED** [review]

File: proxy/src/bin/pg_sni_router.rs [hunk 1]
```diff
@@ -168,6 +168,11 @@ async fn task_main(
                     .instrument(tracing::info_span!("handle_client", ?session_id))
                 );
             }
+            Some(Err(e)) = connections.join_next() => {
```
Comment (koivunej) [inline proxy/src/bin/pg_sni_router.rs:171]: How will this behave if we have no connections...? Will it not busyloop?

**Review by arpad-m — APPROVED** [review]
Good catch! Also @koivunej good catch :)

**Comment by koivunej** [comment]
Now I guess we can close #4672 with this PR?
