### PR TITLE
dube: timeout individual layer evictions, log progress and record metrics

### LINKED ISSUE #6928: layer: unimplemented support for evicting wanted deleted layers
As seen on 2024-02-27, evictions started hanging, and so deletions started hanging, disk usage based eviction task got stuck, and manual intervention was required.

Initial suspicion was wrong, only discovered one obviously missing metric update in: #6931.

Later realized it was the wanted deleted layers inability to communicate anything to `Layer::evict_and_wait` which was the cause of the hangs.

Slack channel: #temp-2024-02-27-stuck-disk-usage-based-eviction

### PR DESCRIPTION
**Pull request by koivunej**
Because of bugs evictions could hang and pause disk usage eviction task. One such bug is known and fixed #6928. Guard each layer eviction with a modest timeout deeming timeouted evictions as failures, to be conservative.

In addition, add logging and metrics recording on each eviction iteration:
- log collection completed with duration and amount of layers
    - per tenant collection time is observed in a new histogram
    - per tenant layer count is observed in a new histogram
- record metric for collected, selected and evicted layer counts
- log if eviction takes more than 10s
- log eviction completion with eviction duration

Additionally remove dead code for which no dead code warnings appeared in earlier PR.

Follow-up to: #6060.

### CODE REVIEW

**Comment by koivunej** [comment]
Should do the same for eviction_task.

File: pageserver/src/disk_usage_eviction_task.rs [hunk 1]
```diff
@@ -529,6 +547,44 @@ pub(crate) async fn disk_usage_eviction_task_iteration_impl<U: Usage>(
...
+            match res {
+                Ok(tuple) => {
+                    tracing::info!(%elapsed_ms, "completed");
+                    return tuple;
+                }
+                Err(_timeout) => {
+                    tracing::info!(%elapsed_ms, "still ongoing");
+                }
+            }
+        }
```
Comment (problame) [inline pageserver/src/disk_usage_eviction_task.rs:582]: This could be DRY with

```rust
for i in 0.. {
    match tokio::time::timeout(maximum_expected, &mut evict_layers).await {
        Ok(tuple) => {
            if i > 0 {
                // make noise only if we logged "still going" earlier"
                info!("completed");
            }
            return tuple;   
        }
        Err(_timeout) => {
            tracing::info!(
                elapsed_ms = started_at.elapsed().as_millis(),
                "still ongoing"
            );
            continue;
        }
    }

}
```

File: pageserver/src/disk_usage_eviction_task.rs [hunk 2]
```diff
@@ -479,7 +478,15 @@ pub(crate) async fn disk_usage_eviction_task_iteration_impl<U: Usage>(
...
-                    Ok(Err((file_size, EvictionError::NotFound | EvictionError::Downloaded))) => {
+                    Ok(Err((
+                        file_size,
+                        Some(EvictionError::NotFound | EvictionError::Downloaded),
+                    ))) => {
+                        evictions_failed.file_sizes += file_size;
+                        evictions_failed.count += 1;
+                    }
+                    Ok(Err((file_size, None))) => {
+                        // count timeouted as failed evictions even if they might complete later
```
Comment (problame) [inline pageserver/src/disk_usage_eviction_task.rs:489]: I would strongly prefer an enum that spells out the three different Ok() cases.

Just look at the type of `next`, way too much nesting IMO.

* `Ok(Ok(_))` => `EvictLayerResult::Succeeded`
* `Ok(Err(_, Some(_)))` => `EvictLayerResult::Failed`
* `Ok(Err(_, None))` => `EvictLayerResult::EvictCallTimedOut`

Comment (problame) [reply pageserver/src/disk_usage_eviction_task.rs:489]: Also, the treatment of `Ok(Err(_, Some()))` and `Ok(Err(_, None))` seems to be the same?

**Review by problame — APPROVED** [review]
While convincing myself of the cancel-safety of evict_layers, I noticed that it leaks the `JoinSet` `js` on cancellation. 
Well, it does `join_handle.abort()` on each task.

So, I think `secondary_tenant.evict_layer()` has probably not been audited for cancellation safety.
I don't know the invariants, but, it doesn't look cancel safe (could be cancelled by the runtime when returning Poll::Ready from `remove_file`). It's a pre-existing issue though, and secondaries aren't prod-enabled yet, so, let's punt that to a new issue. At a mininum, the the `SecondaryTenant::evict_layer` function needs a comment stating it promises to be cancel-safe.

**Comment by koivunej** [comment]
> So, I think `secondary_tenant.evict_layer()` has probably not been audited for cancellation safety.

Excellent point. This PR was done before secondary tenants or at least their eviction, and I did not revisit it while fixing conflicts.

File: pageserver/src/disk_usage_eviction_task.rs (hunk 2 above)
Comment (koivunej) [reply pageserver/src/disk_usage_eviction_task.rs:489]: > Also, the treatment of Ok(Err(_, Some())) and Ok(Err(_, None)) seems to be the same?

Per description yes that is the case. I think I wanted to duplicate them, but perhaps it does no good.

Comment (koivunej) [reply pageserver/src/disk_usage_eviction_task.rs:489]: > I would strongly prefer an enum that spells out the three different Ok() cases.

Aah yes, join error wrapping. Ok, I see what you mean.

Comment (koivunej) [reply pageserver/src/disk_usage_eviction_task.rs:489]: I'll probably push the timeout to `Layer::evict_and_wait` and so I'll have it for both this and eviction_task.

File: pageserver/src/disk_usage_eviction_task.rs (hunk 1 above)
Comment (koivunej) [reply pageserver/src/disk_usage_eviction_task.rs]: I removed the repeated nagging after first writing out this PR I was annoyed seeing those in prod in other context. Now there's one nag, then final completion report.

File: pageserver/src/disk_usage_eviction_task.rs (hunk 2 above)
Comment (koivunej) [reply pageserver/src/disk_usage_eviction_task.rs]: Pushed, and added a new grandiose "smoke_test" which "tests" this, though quite leniently.

File: pageserver/src/metrics.rs [hunk 3]
```diff
@@ -2474,6 +2474,64 @@ pub(crate) mod tenant_throttling {
...
+                "Amount of layers selected"
+            )
+            .unwrap();
+
+            let layers_evicted = register_int_counter!(
+                "pageserver_dube_evicted_layers_total",
+                "Amount of layers successfully evicted"
+            )
+            .unwrap();
+
```
Comment (koivunej) [inline pageserver/src/metrics.rs:2521]: I have basically no idea about the buckets, they are guesses. I will change them after first few runs.

With the counters I was hoping to catch a these updating staggered but perhaps it's just a hope in case we have more than 1 iteration per sampling_rate. If you have better ideas, please suggest. At least you could get a hopefully steady `increase(...)` in that case.

File: pageserver/src/tenant/timeline/eviction_task.rs [hunk 4]
```diff
@@ -296,6 +304,7 @@ impl Timeline {
                 if stats.candidates == stats.not_evictable {
                     debug!(stats=?stats, "eviction iteration complete");
                 } else if stats.errors > 0 || stats.not_evictable > 0 {
+                    // do not warn on timeouts, in overloaded situations they are normal
                     warn!(stats=?stats, "eviction iteration complete");
```
Comment (problame) [inline pageserver/src/tenant/timeline/eviction_task.rs:308]: It's an abnormal condition, we should warn in the case of eviction timeouts.
We want it to stand out in the logs.
The level warn vs info doesn't make a difference to log volume.

File: pageserver/src/tenant/secondary.rs [hunk 5]
```diff
@@ -187,35 +192,57 @@ impl SecondaryTenant {
...
+            } else {
+                deleted
+                    .map(|()| true)
+                    .fatal_err("Deleting layer during eviction")
+            };
+
+            if !deleted {
+                // skip updating accounting and putting perhaps later timestamp
+                return;
+            }
```
Comment (problame) [inline pageserver/src/tenant/secondary.rs:221]: I think a `match` would be simpler to read.

File: pageserver/src/tenant/timeline.rs [hunk 6]
```diff
@@ -1466,10 +1466,14 @@ impl Timeline {
             return Ok(None);
         };
 
-        match local_layer.evict_and_wait().await {
+        // curl has this by default
+        let timeout = std::time::Duration::from_secs(120);
+
+        match local_layer.evict_and_wait(timeout).await {
```
Comment (problame) [inline pageserver/src/tenant/timeline.rs:1472]: We know it's cancel-safe, let's just use Duration::MAX or whatever it is, and I suppose this method and `evict_and_wait` should take a CancellationToken.

I can see us use this API in an emergency Python script which doesn't want any timeout.

If you disagree with that, at least have a better comment that sets context why `curl` is important .


```suggestion
        // mgmt APIs like this one are typically called from curl, which has a 120 timeout by default
        let timeout = std::time::Duration::from_secs(120);

        match local_layer.evict_and_wait(timeout).await {
```

File: pageserver/src/metrics.rs [hunk 7]
```diff
@@ -2474,6 +2474,64 @@ pub(crate) mod tenant_throttling {
...
+    }
+
+    impl Default for Metrics {
+        fn default() -> Self {
+            let tenant_collection_time = register_histogram!(
+                "pageserver_dube_tenant_collection_seconds",
+                "Time spent collecting layers from a tenant -- not normalized by collected layer amount",
+                vec![0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0]
+            )
+            .unwrap();
```
Comment (problame) [inline pageserver/src/metrics.rs:2495]: Please don't use a random acronym that you made up (`dube`) which could also be confused for `duplicate` by some readers.

If you insist on an acronym, make it all-caps, i.e., `pageserver_DUBE_...` . But it already looks so weird & against conventions, I would really prefer it spelled out.

That way, fuzzy autocomplete in grafana will find it, etc.

Also, the help text should mention disk-usage-base eviction, e.g.


```suggestion
            let tenant_collection_time = register_histogram!(
                "pageserver_disk_usage_based_eviction_tenant_collection_seconds",
                "Time that disk-usage-based eviction spent collecting layers from a tenant -- not normalized by collected layer amount",
                vec![0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0, 10.0]
            )
            .unwrap();
```

Comment (problame) [reply pageserver/src/metrics.rs:2495]: Same applies to other metrics.

File: pageserver/src/disk_usage_eviction_task.rs [hunk 8]
```diff
@@ -477,9 +488,15 @@ pub(crate) async fn disk_usage_eviction_task_iteration_impl<U: Usage>(
...
                     }
-                    Ok(Err((file_size, EvictionError::NotFound | EvictionError::Downloaded))) => {
+                    Ok(Err((
+                        file_size,
+                        EvictionError::NotFound
+                        | EvictionError::Downloaded
+                        | EvictionError::Timeout,
+                    ))) => {
                         evictions_failed.file_sizes += file_size;
                         evictions_failed.count += 1;
```
Comment (problame) [inline pageserver/src/disk_usage_eviction_task.rs:501]: No metric for the error case because we already have metrics inside `layer.rs` ?

**Review by problame — APPROVED** [review]
Love the smoke test, great work!

I like the added metrics, not just their names.

Not sure why you went for a `timeout` parameter instead of making callers who care use `tokio::time::timeout`, but :shrug:

File: pageserver/src/metrics.rs (hunk 7 above)
Comment (koivunej) [reply pageserver/src/metrics.rs:2495]: Ok, will expand.

File: pageserver/src/disk_usage_eviction_task.rs (hunk 8 above)
Comment (koivunej) [reply pageserver/src/disk_usage_eviction_task.rs:501]: No, I did not add that. But we do count the started, completed and cancelled evictions.

An eviction can be cancelled if you have a read after you've wanted to evict something which is not yet deleted from disk (read wins).

Timeout will not cause a cancelled eviction. Like I wanted to do originally: have just `evict` instead of `evict_and_wait` but I failed to see a way to fix the tests.

File: pageserver/src/tenant/storage_layer/layer/tests.rs [hunk 9]
```diff
@@ -1,13 +1,164 @@
...
+    };
+
+    assert_eq!(img_before, img_after);
+
+    // evict_and_wait can timeout, but it doesn't cancel the evicting itself
+    //
+    // ZERO for timeout works, because evicting will always need to use spawn_blocking which takes
+    // non-zero time.
+    match layer.evict_and_wait(std::time::Duration::ZERO).await {
+        Ok(()) => { /* but sometimes this spawn_blocking is fast enough */ }
```
[the remark this answers is not in the document]
Comment (koivunej) [reply pageserver/src/tenant/storage_layer/layer/tests.rs:92]: Yes it sadly was taken at runtime after running this test quite a lot of times. Can check this, maybe it was caused by me using `start_paused = true` originally -- would prefer to mark this as unreachable.

File: pageserver/src/disk_usage_eviction_task.rs (hunk 8 above)
Comment (problame) [reply pageserver/src/disk_usage_eviction_task.rs:501]: Ok just wanted to point out that it seems like we're not counting the errors explicitly. 

> No, I did not add that. But we do count the started, completed and cancelled evictions.

Are you saying if we need error count we can get it by `error_count = started - completed`

Good enough for me, might be worth a block comment in the `metrics.rs` , but maybe it's obvious.

File: pageserver/src/tenant/storage_layer/layer/tests.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (koivunej) [reply pageserver/src/tenant/storage_layer/layer/tests.rs]: This was mostly Ok(()) because tokio::time::timeout prioritizing actual work over the timeout.

I added consuming all threads before, release, and all threads after for proper synchronization, like I did for the `residency_check_while_evict_and_wait_on_clogged_spawn_blocking` in [eaa81c0](https://github.com/neondatabase/neon/pull/6131/commits/eaa81c07a0fc836afd45cd1aaea484c8df487ad2)

File: pageserver/src/tenant/timeline/eviction_task.rs (hunk 4 above)
Comment (koivunej) [reply pageserver/src/tenant/timeline/eviction_task.rs]: Oki, made it a warning.

File: pageserver/src/tenant/secondary.rs (hunk 5 above)
Comment (koivunej) [reply pageserver/src/tenant/secondary.rs:221]: Did not touch this.

File: pageserver/src/tenant/timeline.rs (hunk 6 above)
Comment (koivunej) [reply pageserver/src/tenant/timeline.rs:1472]: I will reconsider this when perhaps making the timeout external to `evict_and_wait` once again in the future.

File: pageserver/src/metrics.rs (hunk 7 above)
Comment (koivunej) [reply pageserver/src/metrics.rs]: [0101b55](https://github.com/neondatabase/neon/pull/6131/commits/0101b55ae5738b536fd0769e439e2e3a34f70392)

failed to repeat it in description. I don't think anyone reads the descriptions without knowing what metric they are describing.

File: pageserver/src/disk_usage_eviction_task.rs (hunk 8 above)
Comment (koivunej) [reply pageserver/src/disk_usage_eviction_task.rs:501]: > Are you saying if we need error count we can get it by error_count = started - completed

No, it's `hanging_count = start - completed - sum by (instance) (cancelled)`. As I've been monitoring the data, it's quite difficult to setup a warning or alert because it can legitimately hang for multiple samples, then some other eviction could hang for 1..n samples so the count stays non-zero.

Comment (koivunej) [reply pageserver/src/disk_usage_eviction_task.rs:501]: Also block comment not added -- block comments are bad anyways, and the dashboard has been using the correct calculation for N months.

**Comment by koivunej** [comment]
> Not sure why you went for a `timeout` parameter instead of making callers who care use `tokio::time::timeout`, but 🤷

I was thinking it's the mandatory nature makes sense here. Waiting is a nice to have, it's not required except for our tests. Timeout does not cancel it.

**Comment by koivunej** [comment]
Rebase needed for build-image tools.
