### PR TITLE
Retry remote downloads.

### LINKED ISSUE #3112: Implement retries for S3 download when loading a tenant
Currently, when the pageserver is restarted, we perform an S3 list operation for each tenant and download the index file for each timeline. (We also download all missing layer files, but we're going to stop doing that when the on-demand download PR lands.) If those operations fail, the tenant is marked as Broken, and manual intervention is required to reload it again. We should perform at least a few retries before giving up, it's fairly normal to have transient network problem that cause S3 operations to occasionally fail.

### PR DESCRIPTION
**Pull request by hlinnaka**
Remote operations fail sometimes due to network failures or other external reasons. Add retry logic to all the remote downloads, so that a transient failure at pageserver startup or tenant attach doesn't cause the whole tenant to be marked as Broken.

Like in the uploads retry logic, we print the failure to the log as a WARNing after three retries, but keep retrying. We will retry up to 10 times now, before returning the error to the caller.

To test the retries, I created a new RemoteStorage wrapper that simulates failures, by returning an error for the first N times that a remote operation is performed. It can be enabled by setting a new "test_remote_failures" option in the pageserver config file.

Fixes #3112

### CODE REVIEW

File: pageserver/src/bin/pageserver.rs [hunk 1]
```diff
@@ -277,12 +277,30 @@ fn start_pageserver(conf: &'static PageServerConf) -> anyhow::Result<()> {
...
+                info!(
+                    "Simulating remote failures for first {} attempts of each op",
+                    conf.test_remote_failures
+                );
+                Some(GenericRemoteStorage::unreliable_wrapper(
+                    remote_storage,
+                    conf.test_remote_failures,
+                ))
+            } else {
+                anyhow::bail!("test_remote_failures option is not available because pageserver was compiled without the 'testing' feature");
```
Comment (shanyp) [inline pageserver/src/bin/pageserver.rs:295]: Is it possible to hide this test code in a RemoteStorageFactory that will be the only place to mix test and production code?

File: test_runner/regress/test_remote_storage.py [hunk 2]
```diff
@@ -118,6 +114,14 @@ def test_remote_storage_backup_and_restore(
         wait_for_upload(client, tenant_id, timeline_id, current_lsn)
         log.info(f"upload of checkpoint {checkpoint_number} is done")
 
+    # Check that we had to retry the uploads
```
Comment (shanyp) [inline test_runner/regress/test_remote_storage.py:117]: We may want to add a UUID to each operation result, allowing us to use it as breadcrumbs in investigations and in tests as well, for example, the log_cotains will look for a specific upload operation

File: pageserver/src/storage_sync2/download.rs [hunk 3]
```diff
@@ -52,21 +59,27 @@ pub async fn download_layer_file<'a>(
...
-        format!(
-            "Failed to open a download stream for layer with remote storage path '{remote_path:?}'"
-        )
-    })?;
-    let bytes_amount = tokio::io::copy(&mut download.download_stream, &mut destination_file).await.with_context(|| {
-        format!("Failed to download layer with remote storage path '{remote_path:?}' into file {temp_file_path:?}")
-    })?;
+    let (mut destination_file, bytes_amount) = download_retry(
+        || async {
+            // TODO: this doesn't use the cached fd for some reason?
```
Comment (shanyp) [inline pageserver/src/storage_sync2/download.rs:64]: shouldn't each TODO have a Github issue number attached to it ?

File: pageserver/src/bin/pageserver.rs (hunk 1 above)
Comment (hlinnaka) [reply pageserver/src/bin/pageserver.rs:295]: Hmm, I guess it would make to put this in a separate function, the `start_pageserver` function is quite long already.

I also opened https://github.com/neondatabase/neon/pull/3145 for some minor cleanups around here.

File: libs/remote_storage/src/simulate_failures.rs [hunk 4]
```diff
@@ -0,0 +1,123 @@
+//! This module provides a wrapper around a real RemoteStorage implementation that
+//! causes some operations to fail. For testing purposes.
+use std::collections::hash_map::Entry;
+use std::collections::HashMap;
+use std::sync::Mutex;
```
[the remark this answers is not in the document]
Comment (SomeoneToIgnore) [reply libs/remote_storage/src/simulate_failures.rs:5]: Also, I feel somewhat odd about `Mutex` usage here in general: feels like that could influences the way the requests to the remote storage come (due to having them more ordered?), wonder if that makes some test results fake.

File: pageserver/src/storage_sync2/download.rs (hunk 3 above)
Comment (hlinnaka) [reply pageserver/src/storage_sync2/download.rs:64]: We don't have such a policy. Maybe we should, but that's another discussion :-). Note this TODO isn't new, it's just moved around.

Comment (koivunej) [reply pageserver/src/storage_sync2/download.rs:64]: I added this TODO in the first week, could be just removed.

File: libs/remote_storage/src/simulate_failures.rs [hunk 5]
```diff
@@ -0,0 +1,123 @@
+//! This module provides a wrapper around a real RemoteStorage implementation that
+//! causes some operations to fail. For testing purposes.
```
Comment (SomeoneToIgnore) [inline libs/remote_storage/src/simulate_failures.rs:2]: > some

Let's describe how these operations fail and have.

Ideally, would be cool to have a unit test on that, but feels odd to test a test code.

File: test_runner/regress/test_remote_storage.py (hunk 2 above)
Comment (koivunej) [reply test_runner/regress/test_remote_storage.py:117]: :+1: would very much be fan of deconstructing all outcomes into internally pubsubbed events with correlation and causation id linkage to control plane requests or other inputs to the system (timed actions) -- hoping to prototype something along these lines next year :) I think it's quite a large jump however from current setup.

**Review by koivunej — APPROVED** [review]
> To test the retries, I created a new RemoteStorage wrapper that simulates failures, by returning an error for the first N times that a remote operation is performed.

I think this is a good idea.

I would had preferred the retrying-functionality to be within the s3_bucket but because we give out the stream that doesn't work out.

File: libs/remote_storage/src/simulate_failures.rs [hunk 6]
```diff
@@ -0,0 +1,123 @@
...
+use std::collections::hash_map::Entry;
+use std::collections::HashMap;
+use std::sync::Mutex;
+
+use crate::{Download, DownloadError, RemotePath, RemoteStorage, StorageMetadata};
+
+pub struct UnreliableWrapper {
+    inner: crate::GenericRemoteStorage,
+
+    fail_first: u64,
```
Comment (SomeoneToIgnore) [inline libs/remote_storage/src/simulate_failures.rs:12]: NIT: the naming is somewhat confusing to me, I always try to read it as `fail_fast` 🙂 
Maybe, `attempts_to_fail`?

File: pageserver/src/bin/pageserver.rs [hunk 7]
```diff
@@ -277,12 +277,30 @@ fn start_pageserver(conf: &'static PageServerConf) -> anyhow::Result<()> {
...
+            }
+        } else {
+            //Some(remote_storage)
```
Comment (SomeoneToIgnore) [inline pageserver/src/bin/pageserver.rs:298]: Some leftovers, I think this should be returned back.
Super odd that the tests did not fail...

I also agree with the comment above, that the init code is odd.
I think, all related remote storage code should be barred behind `#[cfg(testing)]` feature ideally, to cut it away statically.
If we follow with the special error type for the simulated failure and will add a new variant into `DownloadError`, that variant could be also compiled out, IIRC, same as the config-related code.

**Review by SomeoneToIgnore — CHANGES_REQUESTED** [review]
I see one approve and disagree with a few points, so marking the PR.
Will continue looking.

File: pageserver/src/bin/pageserver.rs (hunk 7 above)
Comment (hlinnaka) [reply pageserver/src/bin/pageserver.rs]: >Some leftovers, I think this should be returned back.

Oops, yes.

> Super odd that the tests did not fail...

Shows that we have retries in all the right places now :-).

File: libs/remote_storage/src/simulate_failures.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (hlinnaka) [reply libs/remote_storage/src/simulate_failures.rs:5]: We've discussed this before: there's nothing wrong with using `std::sync::Mutex` from async code per se. See https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html#which-kind-of-mutex-should-you-use. This Mutex is not held for long, it only protects the hash map.

If you try try to do more complicated things while holding a Mutex, like use `Runtime::block_on` or something else that involves tokio, that's when things get murky.

File: test_runner/regress/test_remote_storage.py (hunk 2 above)
Comment (SomeoneToIgnore) [reply test_runner/regress/test_remote_storage.py:117]: Also, we know how many retries exactly we had to do, might assert that too.

File: test_runner/regress/test_tenant_detach.py [hunk 8]
```diff
@@ -32,6 +32,58 @@ def do_gc_target(
...
 
+# Basic detach and re-attach test
+@pytest.mark.parametrize("remote_storage_kind", available_remote_storages())
+def test_tenant_reattach(
+    neon_env_builder: NeonEnvBuilder,
+    remote_storage_kind: RemoteStorageKind,
+):
+    neon_env_builder.enable_remote_storage(
+        remote_storage_kind=remote_storage_kind,
+        test_name="test_tenant_redownloads_truncated_file_on_startup",
```
Comment (SomeoneToIgnore) [inline test_runner/regress/test_tenant_detach.py:43]:
```suggestion
        test_name="test_tenant_reattach",
```

Wonder, if we should care about this parameter at all, due to our double ID randomness.

File: libs/remote_storage/src/simulate_failures.rs [hunk 9]
```diff
@@ -0,0 +1,123 @@
...
+        }
+    }
+
+    ///
+    /// Common functionality for all operations.
+    ///
+    /// On the first attempts of this operation, return an error. After 'fail_first'
+    /// attempts, let the operation go ahead, and clear the counter.
+    ///
+    fn attempt(&self, op: RemoteOp) -> anyhow::Result<u64> {
```
[the remark this answers is not in the document]
Comment (hlinnaka) [reply libs/remote_storage/src/simulate_failures.rs:42]: > I think that is the root cause of the discussion, and that anyhow::Error parameter in From impl comes from this anyhow::Result.

The reason I added the `From` impl is that I changed the return type of `list_prefixes` from `anyhow::Result` to `Result<, DownloadError>`. Without the From, have to change the ? calls in `list_prefixes` to `map_err`.

I'm not sure about a separate SimulatedFailure error type, but it would be useful to distingush between "retryable" and "non-retryable" errors. For example, if you use and invalid parameter, or the object doesn't exist, it's never going to succeed and there's no point in retrying it. But if the network is down, that should be retried. That would need a lot more work though.

**Review by SomeoneToIgnore — COMMENTED** [review]
Looks nice otherwise.

File: libs/remote_storage/src/simulate_failures.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (SomeoneToIgnore) [reply libs/remote_storage/src/simulate_failures.rs:5]: Yeah, still somewhat uneasy about that, but since it's test code, let's see how it tests.

File: libs/remote_storage/src/simulate_failures.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (SomeoneToIgnore) [reply libs/remote_storage/src/simulate_failures.rs:42]: Yes, error type handling requries more work than `anyhow` and we're supposed to have somebody to outline the module borders and make good errors on that borders.
This PR does something opposite and that's why it feels odd.

Yet, the idea of the retryable operations seems also interesting, so feel free to resolve if you think that should be the vector, not the custom variants for test cases.

[the remark this answers is not in the document]
Comment (hlinnaka) [reply libs/remote_storage/src/simulate_failures.rs:42]: >The reason I added the From impl is that I changed the return type of list_prefixes from anyhow::Result to Result<, DownloadError>. Without the From, have to change the ? calls in list_prefixes to map_err.

And `download_layer_file` too

[the remark this answers is not in the document]
Comment (hlinnaka) [reply libs/remote_storage/src/simulate_failures.rs]: Ok, removed the From impl now, and used `map_err`s instead. This would benefit from more distinguishing retryable and non-retryable errors more carefully, but that's a nice-to-have. Doing some unnecessary retries before failing hard is not a big deal.

File: libs/remote_storage/src/simulate_failures.rs (hunk 6 above)
Comment (hlinnaka) [reply libs/remote_storage/src/simulate_failures.rs]: renamed

File: pageserver/src/bin/pageserver.rs (hunk 7 above)
Comment (hlinnaka) [reply pageserver/src/bin/pageserver.rs]: Fixed that leftover, and rebased this over PR #3145.

Comment (hlinnaka) [reply pageserver/src/bin/pageserver.rs]: > I think, all related remote storage code should be barred behind #[cfg(testing)] feature ideally, to cut it away statically.
If we follow with the special error type for the simulated failure and will add a new variant into DownloadError, that variant could be also compiled out, IIRC, same as the config-related code.

I know we disagree on this, but I'd rather go in the opposite direction, per https://github.com/neondatabase/neon/pull/3030. Conditionally-compiled code is annoying, as you need to compile the code with all combinations of the feature flags to make sure that all the variants compile. Some dead code in production binaries doesn't do any harm.

File: pageserver/src/bin/pageserver.rs (hunk 1 above)
Comment (hlinnaka) [reply pageserver/src/bin/pageserver.rs]: Moved this initialization to a separate function

**Comment by SomeoneToIgnore** [comment]
Two more general thoughts (not for this PR):

* the only place that actually needs retries is S3 now (remote_storage could happen to be some NFS though, yet unlikely), so we might want to bring the retrying wrapper closer (into?) the `GenericRemoteStorage`.
This would make us to move all the failure code into the storage itself, presumably as

```rust
#[not(cfg(testing))]
fn run_operation(op) -> Result<...> {
    op.await
}

#[cfg(testing)]
fn run_operation(op) -> Result<...> {
    if self.failures(op) > ... {}
}
```

IMO, quite simplifes the whole picture and might help with the type discussions.

* If I've got the code right, the `test_remote_failures=1` makes the remote storage to do `"error", "successful op"` in a loop per operation. We now don't detect such cycles, but they seem to be relatively important.
We can add a metric to track the general error numbers: if they occur to much, we can potentially spot it in the metrics.

**Review by SomeoneToIgnore — APPROVED** [review]

File: test_runner/regress/test_remote_storage.py (hunk 2 above)
Comment (hlinnaka) [reply test_runner/regress/test_remote_storage.py:117]: Created a new issue to track that idea, it seems out of scope for this PR
