### PR TITLE
JWT logging improvements

### LINKED ISSUE #5820: useless logging of `jwt auth succeeded for scope: ...`
We should never log these, instead we could log failures at WARN to pick up on misconfigurations and someone hammering on all nodes but those would never need stacktraces.

Example:

```
2023-11-08T05:27:24.937995Z  INFO page_service_conn_main{peer_addr=10.8.45.223:54680}: jwt auth succeeded for scope: Tenant by tenant id: Some(X)
```

The scope is irrelevant. If we keep on logging these someone might be inclined to write tests which assert that the log message appears, which is most certainly the wrong way to assert that auth(z) succeeded.

### PR DESCRIPTION
**Pull request by arpad-m**
* lower level on auth success from info to debug (fixes #5820)
* don't log stacktraces on auth errors (as requested on slack)

### CODE REVIEW

File: libs/utils/src/auth.rs [hunk 1]
```diff
@@ -65,6 +65,26 @@ impl std::fmt::Debug for SwappableJwtAuth {
...
+    fn from(_value: AuthError) -> Self {
+        // Don't pass on the value of the AuthError as a precautionary measure.
+        // Being intentionally vague in public error communication hurts debugability
+        // but it is more secure.
+        ApiError::Forbidden("JWT authentication error".to_string())
+    }
+}
+
+//impl std::error::Error for AuthError {}
+
```
Comment (koivunej) [inline libs/utils/src/auth.rs:87]:
```suggestion
```

File: libs/utils/src/auth.rs [hunk 2]
```diff
@@ -123,9 +143,9 @@ impl JwtAuth {
             }
         }
         if let Some(res) = res {
-            res.map_err(anyhow::Error::new)
+            res.map_err(|e| AuthError(Cow::Owned(e.to_string())))
```
Comment (koivunej) [inline libs/utils/src/auth.rs:146]: I was going to ask about this but later on it's formatted static `ApiError::Forbidden("JWT ...".to_string())` -- is this form ever logged by something? I don't at least see it in case it was meant to be logged.

**Review by petuhovskiy — APPROVED** [review]

File: libs/utils/src/auth.rs [hunk 3]
```diff
@@ -65,6 +65,26 @@ impl std::fmt::Debug for SwappableJwtAuth {
...
+}
+
+impl From<AuthError> for ApiError {
+    fn from(_value: AuthError) -> Self {
+        // Don't pass on the value of the AuthError as a precautionary measure.
+        // Being intentionally vague in public error communication hurts debugability
+        // but it is more secure.
+        ApiError::Forbidden("JWT authentication error".to_string())
+    }
+}
```
[the remark this answers is not in the document]
Comment (arpad-m) [reply libs/utils/src/auth.rs:84]: Yes, it was an anyhow Error and then got converted into `InternalServerError`.

File: libs/utils/src/auth.rs (hunk 2 above)
Comment (koivunej) [reply libs/utils/src/auth.rs:144]: This is now logged by query error logging.

Comment (koivunej) [reply libs/utils/src/auth.rs:144]: For ApiError [8948a7f](https://github.com/neondatabase/neon/pull/5823/commits/8948a7f0ac03a253317bed87a93cf79070f6acf5) logs it now in addition to the ApiError conversion time logging.

**Review by koivunej — APPROVED** [review]

**Comment by arpad-m** [comment]
There is span-less errors in `test_output/test_pageserver_multiple_keys\[debug-pg16\]/repo/pageserver_1/pageserver.log`, which this PR changes to warnings. In a call with @koivunej we agreed that this PR adds TODOs but doesn't address this directly.
