### PR TITLE
Reduce the logging level when PG client disconnected to INFO

### LINKED ISSUE #1683: Reduce noise in log for client disconnects
Lots of messages like this in the pageserver log currently:

```
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]: 2022-05-10T04:18:56.919335Z ERROR Thread 'serving Page Service thread' exited with error: Connection reset by peer (os error 104)
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]: Stack backtrace:
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:    0: <T as core::convert::Into<U>>::into
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:              at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/convert/mod.rs:540:9
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:       zenith_utils::pq_proto::FeMessage::read_fut::{{closure}}
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:              at /home/circleci/project/zenith_utils/src/pq_proto.rs:147:38
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:       <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:              at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/future/mod.rs:80:19
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:    1: <zenith_utils::sync::SyncFuture<S,T> as core::future::future::Future>::poll
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:              at /home/circleci/project/zenith_utils/src/sync.rs:67:9
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:       zenith_utils::sync::SyncFuture<P,T>::wait
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:              at /home/circleci/project/zenith_utils/src/sync.rs:103:15
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:    2: zenith_utils::pq_proto::FeMessage::read
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:              at /home/circleci/project/zenith_utils/src/pq_proto.rs:126:9
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:    3: zenith_utils::postgres_backend::PostgresBackend::read_message
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:              at /home/circleci/project/zenith_utils/src/postgres_backend.rs:239:45
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:    4: zenith_utils::postgres_backend::PostgresBackend::run_message_loop
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:              at /home/circleci/project/zenith_utils/src/postgres_backend.rs:278:19
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:    5: zenith_utils::postgres_backend::PostgresBackend::run
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:              at /home/circleci/project/zenith_utils/src/postgres_backend.rs:265:19
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:    6: pageserver::page_service::page_service_conn_main
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:              at /home/circleci/project/pageserver/src/page_service.rs:280:5
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:       pageserver::page_service::thread_main::{{closure}}
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:              at /home/circleci/project/pageserver/src/page_service.rs:232:29
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:              at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panic/unwind_safe.rs:271:9
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:    7: std::panicking::try::do_call
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:              at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:       std::panicking::try
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:              at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
May 10 04:18:56 zenith-us-stage-ps-1.local pageserver[9057]:       std::panic::catch_unwind
```
A client closing the connection is more or less expected. Let's stop printing the backtrace for that, and downgrade it to INFO level.

### PR DESCRIPTION
**Pull request by aome510**
Fixes #1683

### CODE REVIEW

**Comment by hlinnaka** [comment]
See also https://github.com/neondatabase/neon/issues/551 for some prior discussion

File: pageserver/src/error.rs [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+        match self {
+            Self::Internal(err) => {
+                write!(f, "internal error {err:?}")
+            }
+            _ => {
+                write!(f, "{self:#}")
+            }
+        }
+    }
+}
```
Comment (hlinnaka) [inline pageserver/src/error.rs:48]: I think this is too high level to make the decision of what to print. In a different context, losing the connection might be very unexpected and would warrant a stacktrace. I think it'd be better to check for the ConnectionReset error somewhere in `page_service_conn_main`, and have it return with Ok, instead of propagating the error to the generic error handler in `thread_wrapper`.

**Review by hlinnaka — CHANGES_REQUESTED** [review]

File: pageserver/src/bin/pageserver.rs [hunk 2]
```diff
@@ -284,9 +284,10 @@ fn start_pageserver(conf: &'static PageServerConf, daemonize: bool) -> Result<()
         None,
         "http_endpoint_thread",
         true,
-        move || {
+        move || -> Result<(), error::Error> {
```
Comment (SomeoneToIgnore) [inline pageserver/src/bin/pageserver.rs:287]: It's a bit odd that an error enum with "postgres" and "internal" variants is used in an **http** thread, we clearly do regular http without postgres involved, so there's something odd here.

File: pageserver/src/error.rs [hunk 3]
```diff
@@ -0,0 +1,61 @@
+//!
+//! The `error` module provides a general [`Error`] struct representing different types of
+//! encountered errors when running the page server.
+//!
+
+use thiserror::Error;
+
+#[derive(Error)]
+pub enum Error {
```
Comment (SomeoneToIgnore) [inline pageserver/src/error.rs:9]: Not sure what are your plans for the usage scope of this var, but still might make sense to name it `PageserverError` at least.

I suspect (but not sure yet), we end up creating multiple `Error` structs/enums in this module: pg errors are a bit different from thread management ones.

File: pageserver/src/error.rs (hunk 1 above)
Comment (SomeoneToIgnore) [reply pageserver/src/error.rs:48]: So yeah, the api user is able to choose himself what to write `{e:?}` or `{e:#}`, we don't want to hide the possibility of doing both, as it's now. 
We can follow anyhow's pattern and print both errors the same way.

**Review by SomeoneToIgnore — COMMENTED** [review]
Some work has to be done in this direction, this start is good.

I fear we might have many discussions about levels, layers and whatnot; not sure if this all is a good way to spend time on this PR.
Let's pick one case where we benefit from such error types and fix it? @LizardWizzard might have some ideas on that front.

File: pageserver/src/error.rs (hunk 1 above)
Comment (aome510) [reply pageserver/src/error.rs:48]: >  In a different context, losing the connection might be very unexpected and would warrant a stacktrace. I think it'd be better to check for the ConnectionReset error somewhere in page_service_conn_main, and have it return with Ok, instead of propagating the error to the generic error handler in thread_wrapper.

Do you mean that losing PG client connection in `page_service_conn_main` is expected, but in other cases, it might be unexpected? 

Note that the `PostgresIOError::ConnectionReset` is only constructed inside the `page_service_conn_main` by looking into the type of error returned by `PostgresBackend::run` function. So if we want to handle this connection error separately and return Ok, constructing this error is redundant.

Comment (aome510) [reply pageserver/src/error.rs:48]: > So yeah, the api user is able to choose himself what to write `{e:?}` or `{e:#}`, we don't want to hide the possibility of doing both, as it's now. 

Note that the printing backtrace is only applied to `anyhow::Error`, e.g if we debug print the `PostgresIOError::ConnectionReset`, it will output ` PostgresIO(ConnectionReset)`

File: pageserver/src/error.rs [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+    #[error("Postgres IO error: {0:?}")]
+    PostgresIO(#[from] PostgresIOError),
```
[the remark this answers is not in the document]
Comment (aome510) [reply pageserver/src/error.rs:11]: I created `PostgresIO` variant to represent read/write errors when interacting while PG clients. atm, it only includes the `ConnectionReset` error. Rust doc mentions that "[std::io::Error is] the error type for I/O operations of the Read, Write, Seek, and associated traits.", so I think it also includes network i/o operations.

File: pageserver/src/bin/pageserver.rs (hunk 2 above)
Comment (aome510) [reply pageserver/src/bin/pageserver.rs:287]: Cannot agree more. This is a result of the lack of typed errors and an attempt to add one without many error variants.

Right now, all the errors returned by this http thread will be categorized as internal.

File: pageserver/src/error.rs (hunk 1 above)
Comment (aome510) [reply pageserver/src/error.rs]: After looking into the code again, I realize that instead of manually implementing the `Debug` trait for the page server errors, I can just modify the how the error is formatted with `fmt::Display`  and update the log codes to format the error using the pretty-print `{:#}` format instead of the debug `{:?}` format.

Changes are implemented in https://github.com/neondatabase/neon/pull/1713/commits/965228e44469ac5e90a55db72a7d04c315a0d088

**Comment by aome510** [comment]
@LizardWizzard I saw your comments on [the previous discussion](https://github.com/neondatabase/neon/issues/551). Do u have any suggestions?

File: pageserver/src/page_service.rs [hunk 5]
```diff
@@ -304,8 +309,21 @@ fn page_service_conn_main(
...
+            .root_cause()
+            .downcast_ref::<io::Error>()
+            .map(|e| e.kind());
+
+        if let Some(io::ErrorKind::ConnectionReset) = root_cause_io_err_kind {
+            error::PageServerError::PostgresIO(PostgresIOError::ConnectionReset)
+        } else {
+            error::PageServerError::Internal(err)
+        }
+    })?;
```
Comment (LizardWizzard) [inline pageserver/src/page_service.rs:325]: can be simplified by removing the question mark and `Ok(())`. Because map err transforms the error to correct type already

File: pageserver/src/thread_mgr.rs [hunk 6]
```diff
@@ -234,13 +234,13 @@ fn thread_wrapper<F>(
         Ok(Err(err)) => {
             if shutdown_process_on_error {
                 error!(
-                    "Shutting down: thread '{}' tenant_id: {:?}, timeline_id: {:?} exited with error: {:?}",
+                    "Shutting down: thread '{}' tenant_id: {:?}, timeline_id: {:?} exited with error: {:#}",
```
Comment (LizardWizzard) [inline pageserver/src/thread_mgr.rs:237]: Here and below. `{:#}` format does not produce backtraces so this changes visible behavior. Is it intentional?

**Review by LizardWizzard — APPROVED** [review]
Thanks! I really like the approach. This way we can gradually transform errors we have to a typed ones instead if using anyhow. 

I've left a few minor comments.

File: pageserver/src/thread_mgr.rs (hunk 6 above)
Comment (aome510) [reply pageserver/src/thread_mgr.rs:237]: Yeah, it's intentional. Backtraces are still logged for internal error as specified in https://github.com/neondatabase/neon/pull/1713/files#diff-07e669dd036171046e713197ceed05a7a8294acfcd68f7ef9ce7a2d4ee056ec0R13-R14.

The idea is that if an error is expected, we can easily trace it by looking into the error message and cause.

File: pageserver/src/error.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (hlinnaka) [reply pageserver/src/error.rs]: Ok. How about `NetworkIOError`? I don't like the Postgres part here because as a server, we don't really know what the client is. For the 'basebackup' command for example, the client is actually the `zenith_ctl` utility that runs in the compute node before Postgres itself.

[the remark this answers is not in the document]
Comment (hlinnaka) [reply pageserver/src/error.rs]: Or just `NetworkError`

**Comment by hlinnaka** [comment]
I must be missing something, but shouldn't there be a `match` of `if-else` statement somewhere that checks whether an error is a NetworkError or other error, and prints the error to the log or not? Or will that be a follow-up PR after this?

**Comment by aome510** [comment]
> I must be missing something, but shouldn't there be a `match` of `if-else` statement somewhere that checks whether an error is a NetworkError or other error, and prints the error to the log or not? Or will that be a follow-up PR after this?

The error is handled here: https://github.com/neondatabase/neon/pull/1713/files#diff-729d00406745f4d630d7a7a49bcc535a9c05b96f0916a65a2efa770a899c1359R320.

And it is printed to the log in: https://github.com/neondatabase/neon/pull/1713/files#diff-25fc407003c5568283a59ab1d94cf6b09b5508916fec6798eed5bde9761cc217R243

**Note**: we change the error type returned by the thread from `anyhow::Error` to the new custom error `PageserverError`. When the `NetworkError` is propagated, it will be printed as "Connection reset by peer" , but when other types of error (internal errors) are propagated, the log will also include stacktrace

**Comment by aome510** [comment]
@hlinnaka @SomeoneToIgnore any updates on this PR?

**Comment by aome510** [comment]
Encounter a weird [CI failure](https://app.circleci.com/pipelines/github/neondatabase/neon/6645/workflows/713ada4a-3e8a-4a8b-9850-0f5a5155ecf5/jobs/67377).

The failure:
```
=================================== FAILURES ===================================
________________ test_pageserver_http_get_wal_receiver_success _________________
[gw1] linux -- Python 3.9.2 /home/circleci/.cache/pypoetry/virtualenvs/zenith-3aSsmiER-py3.9/bin/python
test_runner/batch_others/test_pageserver_api.py:87: in test_pageserver_http_get_wal_receiver_success
    assert res2["last_received_msg_lsn"] > res["last_received_msg_lsn"]
E   TypeError: '>' not supported between instances of 'str' and 'NoneType'
```

**Comment by hlinnaka** [comment]
I stared at this for a while, trying to get used to how it works. Something rubs me the wrong way, and I got it finally: The level of detail that you print should be decided by the code that *handles* the error, not be a property of the error itself. Printing the backtrace as part of the error, or not if it's a NetworkError, feels weird. I think @SomeoneToIgnore was trying to say the same thing.

Aside from the error message and the backtrace, there's the logging level. I think we want to print the client disconnections in INFO or TRACE level, not ERROR. That'd be hard to do in the Error struct itself.

So I propose that instead of this PR, we do just this, in `page_service_conn_main`:
```
    match pgbackend.run(&mut conn_handler) {
        Ok(()) => {
            // we've been requested to shut down
            Ok(())
        },
        Err(err) => {
            let root_cause_io_err_kind = err
                .root_cause()
                .downcast_ref::<io::Error>()
                .map(|e| e.kind());

            // `ConnectionReset` error happens when the Postgres client closes the connection,
            // which is expected.
            if root_cause_io_err_kind == Some(io::ErrorKind::ConnectionReset) {
                info!("Client disconnected");
                Ok(())
            } else {
                Err(err)
            }
        }
    }
```
What do you think?

Now, this means that we don't need the PageServerError enum . Per discussion at https://github.com/neondatabase/neon/issues/551, an enum like that would be nice for other reasons, but it doesn't really help here.

What would be nice, though, is an Error enum in `postgres_backend.rs`. It would be nice to distinguish cases like network I/O errors, connection reset, protocol errors, and authentication failures in `PostgresBackend::run`, and allow the caller to handle those differently. That would get rid of the `downcast_ref` code above to fish the original error, making it simpler. But for now, I think the `downcast_ref` is fine.

**Comment by aome510** [comment]
Reset the branch to implement the change suggested Heikki in [this comment](https://github.com/neondatabase/neon/pull/1713#issuecomment-1136428486).

**Review by hlinnaka — APPROVED** [review]
