### PR TITLE
Remove initdb on timeline delete

### LINKED ISSUE #6226: initdb.tar.zst is not deleted on timeline/tenant deletion
## Steps to reproduce
1. Create a new project, in e.g. eu-central-1
2. Run `show neon.tenant_id`, mark the value down
3. Delete the new project
4. Look in the storage bucket of (this case) eu-central-1 for files from that tenant

## Expected result
All data of that tenant has been deleted

## Actual result
Most data of that tenant has been deleted, except the `initdb.tar.zst`

## Environment
Production

## Logs, links
- One of my own test projects to verify this finding: https://s3.console.aws.amazon.com/s3/buckets/neon-prod-storage-eu-central-1?region=eu-central-1&prefix=pageserver%2Fv1%2Ftenants%2Fd521cfeccc29d52568c9efe512458389%2Ftimelines%2Ffaa6295a342850205f91b4e17e3679ef%2F&showversions=true

### PR DESCRIPTION
**Pull request by arpad-m**
This PR:

* makes `initdb.tar.zst` be deleted by default on timeline deletion (#6226), mirroring the safekeeper: https://github.com/neondatabase/neon/pull/6381
* adds a new `preserve_initdb_archive` endpoint for a timeline, to be used during the disaster recovery process, see reasoning [here](https://github.com/neondatabase/neon/issues/6226#issuecomment-1894574778)
* makes the creation code look for `initdb-preserved.tar.zst` in addition to `initdb.tar.zst`.
* makes the tests use the new endpoint

fixes #6226

### CODE REVIEW

File: pageserver/src/http/routes.rs [hunk 1]
```diff
@@ -1943,6 +1973,9 @@ pub fn make_router(
         .post("/v1/tenant/:tenant_id/ignore", |r| {
             api_handler(r, tenant_ignore_handler)
         })
+        .post("/v1/tenant/:tenant_shard_id/timeline/:timeline_id/preserve_initdb_archive", |r| {
+            api_handler(r, timeline_preserve_initdb_handler)
```
Comment (problame) [inline pageserver/src/http/routes.rs:1977]: `testing_api_handler` ?

File: pageserver/src/tenant/timeline.rs [hunk 2]
```diff
@@ -2850,6 +2850,21 @@ impl Timeline {
...
+        if let Some(remote_client) = &self.remote_client {
+            remote_client
+                .preserve_initdb_archive(
+                    &self.tenant_shard_id.tenant_id,
+                    &self.timeline_id,
+                    &self.cancel,
+                )
+                .await?;
+        } else {
+            tracing::info!("No remote storage configured, but was asked to backup the initdb archive for {} / {}", self.tenant_shard_id.tenant_id, self.timeline_id);
```
Comment (problame) [inline pageserver/src/tenant/timeline.rs:2863]: Why not bail with an error here? It's only called from the mgmt API

**Review by problame — COMMENTED** [review]
Why do we need the optional ability to preserve the initdb across deletions?

AFAICT, the only use case will be `test_compatibility.py` and `test_wal_restore.py`.

Instead of adding this "preservation" logic in Pageserver, why not have the Python tests preserve the `initdb.tar.zst` in the place where you currently call `timeline_preserve_initdb_archive` ?

**Comment by arpad-m** [comment]
> Why do we need the optional ability to preserve the initdb across deletions?

It depends on how control plane wants to implement the WAL disaster recovery process (#5282). If they want to retain the timeline ID instead of choosing a new one, then an ability to preserve the initdb is needed. If control plane and the other involved components of the stack like billing support a feature for a switch of the timeline ID, then this endpoint is not required. I think it might come in handy though. The goal for my project, as Heikki described it, was to provide a toolbox of different methods for recovering from unfortunate situations. Not every tool might always be needed.

File: pageserver/src/tenant/timeline.rs (hunk 2 above)
Comment (arpad-m) [reply pageserver/src/tenant/timeline.rs:2863]: I don't really care either direction, I will change it to bail.

**Comment by problame** [comment]
> If they want to retain the timeline ID instead of choosing a new one, then an ability to preserve the initdb is needed.

How will it be needed? Is there some sort of design doc that I missed?

I don't why we wouldn't simply skip deleting the `initdb.tar.zst` instead of creating a new copy.

**Comment by arpad-m** [comment]
> I don't why we wouldn't simply skip deleting the initdb.tar.zst instead of creating a new copy.

I have wondered about adding a parameter to timeline deletion to allow sparing the initdb archive, but then one would have to pass a parameter deep into the hierarchy of the timeline deletion, which is also a process that is designed to be able to be retried at any step, and continues when the pageserver crashes somewhere during the process. One place where this information is persisted is in the `index_part.json` where there is a `deleted_at` value. It might be possible to add a `keep_initdb_on_delete` boolean flag.

**Comment by arpad-m** [comment]
> How will it be needed? Is there some sort of design doc that I missed?

#5248 is written with a new timeline in mind but what the `test_wal_restore_http` test is doing is basically what I suggest to happen for the initial version of the WAL restore process, as it requires less console changes:

First delete the timeline on the PS, then recreate it with the same timeline ID. That's it. The initdb needs to somehow survive this process, which this PR tries to address via a copy endpoint, but a parameter for the `DELETE` http endpoint also works (but seems overkill to me).

File: pageserver/src/tenant/timeline.rs (hunk 2 above)
Comment (problame) [reply pageserver/src/tenant/timeline.rs:2863]: Still planning to do that?

File: pageserver/src/http/routes.rs [hunk 3]
```diff
@@ -1943,6 +1975,10 @@ pub fn make_router(
         .post("/v1/tenant/:tenant_id/ignore", |r| {
             api_handler(r, tenant_ignore_handler)
         })
+        .post(
+            "/v1/tenant/:tenant_shard_id/timeline/:timeline_id/preserve_initdb_archive",
+            |r| api_handler(r, timeline_preserve_initdb_handler),
+        )
```
Comment (problame) [inline pageserver/src/http/routes.rs:1981]: IIUC this API will be used by the DR workflow, so, it's a committed interface. Should document it in our `openapi_spec.yml`

File: pageserver/src/tenant/remote_timeline_client.rs [hunk 4]
```diff
@@ -1070,6 +1072,27 @@ impl RemoteTimelineClient {
...
+    pub(crate) async fn preserve_initdb_archive(
+        self: &Arc<Self>,
+        tenant_id: &TenantId,
+        timeline_id: &TimelineId,
+        cancel: &CancellationToken,
+    ) -> anyhow::Result<()> {
+        backoff::retry(
+            || async {
+                preserve_initdb_archive(&self.storage_impl, tenant_id, timeline_id, cancel).await
+            },
```
Comment (problame) [inline pageserver/src/tenant/remote_timeline_client.rs:1084]: nit: qualified use, i.e., `upload::preserver_...` would be bette here, because this method has the same name as the function we're calling

**Review by problame — APPROVED** [review]
There's not a single comment explaining that this feature is for DR. Let's fix that before merging this PR. Good place would be in the top-level HTTP API handler, it's the entrypoint for almost all of the code that this PR adds. You could re-use the writing done in https://github.com/neondatabase/neon/pull/6387#issuecomment-1900735708 

Let's also make sure to broadcast knowledge about this preserved initdb to the wider team, e.g., in `#proj-pageserver-disaster-recovery` ; it seems like a slight change in direction from what's written in the RFC.
We could also make an exception and update / add an addendum to the RFC.

File: pageserver/src/tenant/timeline.rs (hunk 2 above)
Comment (arpad-m) [reply pageserver/src/tenant/timeline.rs:2863]: Yes, will do

File: pageserver/src/http/routes.rs (hunk 3 above)
Comment (arpad-m) [reply pageserver/src/http/routes.rs:1986]: Done.

File: pageserver/src/tenant/remote_timeline_client.rs (hunk 4 above)
Comment (arpad-m) [reply pageserver/src/tenant/remote_timeline_client.rs]: Done.

File: pageserver/src/tenant/timeline.rs (hunk 2 above)
Comment (arpad-m) [reply pageserver/src/tenant/timeline.rs]: Done.

File: pageserver/src/http/routes.rs (hunk 1 above)
Comment (arpad-m) [reply pageserver/src/http/routes.rs]: This will be used in production so I don't think it is a good idea.

**Comment by arpad-m** [comment]
I have addressed all the points. Asking again for your opinion to give you an opportunity to give feedback on the yml changes.

**Review by problame — APPROVED** [review]
