### PR TITLE
safekeeper: downgrade interpreted reader errors

### LINKED ISSUE #11027: safekeeper: critical!() can hit on S3 errors
In #10657 one of the critical cases was safekeeper reads:
```
 git blame safekeeper/src/send_interpreted_wal.rs | grep critical
f4cfa725b8 (Erik Grinaker 2025-02-06 11:30:27 +0100   19) use utils::critical;
f4cfa725b8 (Erik Grinaker 2025-02-06 11:30:27 +0100  290)                     .inspect_err(|err| critical!("failed to read WAL record: {err:?}"))
f4cfa725b8 (Erik Grinaker 2025-02-06 11:30:27 +0100  351)             critical!("failed to read WAL record: {err:?}");
```

It turns out that can hit on S3 500s with a backtrace like this:
```
Caused by:
    Failed to download a remote file: download s3 object
    
    Caused by:
        0: service error
        1: unhandled error (InternalError)
        2: Error { code: "InternalError", message: "We encountered an internal error. Please try again.", s3_extended_request_id: "123/456=", aws_request_id: "123123" }
    
    Stack backtrace:
       0: anyhow::error::<impl anyhow::Error>::new
                 at /home/nonroot/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/anyhow-1.0.94/src/backtrace.rs:27:14
       1: remote_storage::s3_bucket::S3Bucket::download_object::{{closure}}
                 at /home/nonroot/libs/remote_storage/src/s3_bucket.rs:305:21
       2: <remote_storage::s3_bucket::S3Bucket as remote_storage::RemoteStorage>::download::{{closure}}
                 at /home/nonroot/libs/remote_storage/src/s3_bucket.rs:807:10
       3: remote_storage::GenericRemoteStorage<alloc::sync::Arc<Other>>::download::{{closure}}
                 at /home/nonroot/libs/remote_storage/src/lib.rs:518:62
       4: safekeeper::wal_backup::read_object::{{closure}}
                 at /home/nonroot/safekeeper/src/wal_backup.rs:536:10
       5: safekeeper::wal_storage::WalReader::open_segment::{{closure}}
                 at /home/nonroot/safekeeper/src/wal_storage.rs:817:71
       6: safekeeper::wal_storage::WalReader::read::{{closure}}
```

### PR DESCRIPTION
**Pull request by erikgrinaker**
## Problem

This `critical!` could fire on IO errors, which is just noisy.

Resolves #11027.

## Summary of changes

Downgrade to error, except for decode errors. These could be either data corruption or a bug, but seem worth investigating either way.

### CODE REVIEW

**Review by jcsp — APPROVED** [review]

File: safekeeper/src/send_interpreted_wal.rs [hunk 1]
```diff
@@ -287,7 +287,13 @@ impl InterpretedWalReader {
                 reader
                     .run_impl(start_pos)
                     .await
-                    .inspect_err(|err| critical!("failed to read WAL record: {err:?}"))
+                    .inspect_err(|err| match err {
+                        // TODO: we may want to differentiate these errors further.
+                        InterpretedWalReaderError::Decode(_) => {
+                            critical!("failed to decode WAL record: {err:?}");
+                        }
```
Comment (VladLazar) [inline safekeeper/src/send_interpreted_wal.rs:294]: We should split up `InterpretedWalReaderError::ReadOrInterpret` into `Read` and `Interpret`.
Interpretation errors should be critical.

**Review by VladLazar — APPROVED** [review]

File: safekeeper/src/send_interpreted_wal.rs (hunk 1 above)
Comment (erikgrinaker) [reply safekeeper/src/send_interpreted_wal.rs:294]: Yeah, but that's going to require a bunch of plumbing since `StreamingWalReader` and all the inner infra currently uses `anyhow::Error`. I'll merge this as-is to get the downgrade in. Are you up for some plumbing? :)
