### PR TITLE
Make test_random_updates and test_read_at_max_lsn compatible with new compaction

### LINKED ISSUE #7287: tiered compaction: can't get last key
Found in #7283, the `test_read_at_max_lsn` test added by #7007 is failing with tiered compaction:

```diff
diff --git a/pageserver/src/tenant.rs b/pageserver/src/tenant.rs
index 0806ef0cf..70b6eaa44 100644
--- a/pageserver/src/tenant.rs
+++ b/pageserver/src/tenant.rs
@@ -3853,6 +3853,7 @@ mod tests {
     use bytes::BytesMut;
     use hex_literal::hex;
     use pageserver_api::keyspace::KeySpace;
+    use pageserver_api::models::CompactionAlgorithm;
     use rand::{thread_rng, Rng};
 
     static TEST_KEY: Lazy<Key> =
@@ -5151,7 +5152,9 @@ mod tests {
 
     #[tokio::test]
     async fn test_read_at_max_lsn() -> anyhow::Result<()> {
-        let harness = TenantHarness::create("test_read_at_max_lsn")?;
+        let mut harness = TenantHarness::create("test_read_at_max_lsn")?;
+        harness.tenant_conf.compaction_algorithm = CompactionAlgorithm::Tiered;
+
         let (tenant, ctx) = harness.load().await;
         let tline = tenant
             .create_test_timeline(TIMELINE_ID, Lsn(0x08), DEFAULT_PG_VERSION, &ctx)
@@ -5163,7 +5166,8 @@ mod tests {
         let test_key = Key::from_hex("010000000033333333444444445500000000").unwrap();
         let read_lsn = Lsn(u64::MAX - 1);
 
-        assert!(tline.get(test_key, read_lsn, &ctx).await.is_ok());
+        let result = tline.get(test_key, read_lsn, &ctx).await;
+        assert!(result.is_ok(), "result is not Ok: {}", result.unwrap_err());
 
         Ok(())
     }
```

originally part of #6768
moved to #7554

### PR DESCRIPTION
**Pull request by arpad-m**
Makes two of the tests work with the tiered compaction that I had to ignore in #7283.

The issue was that tiered compaction actually created image layers, but the keys didn't appear in them as `collect_keyspace` didn't include them. Not a compaction problem, but due to how the test is structured.

Fixes #7287

### CODE REVIEW

**Review by skyzh — APPROVED** [review]

File: pageserver/src/tenant.rs [hunk 1]
```diff
@@ -5119,9 +5149,6 @@ mod tests {
                 )
                 .await?;
             tline.freeze_and_flush().await?;
-            tline
-                .compact(&CancellationToken::new(), EnumSet::empty(), &ctx)
```
Comment (skyzh) [inline pageserver/src/tenant.rs:5123]: is this removal of compaction expected?

Comment (skyzh) [reply pageserver/src/tenant.rs:5123]: ... and I don't see any other compactions running in this test case, so I assume this is rather unexpected?

Comment (arpad-m) [reply pageserver/src/tenant.rs:5123]: It's indeed expected: compaction removes those keys. This sounds scary because the legacy compaction didn't do that: but that's because it never created image layers. the bug is more in collect_keyspace, used both by new and old compaction, returning key ranges that don't contain the written key. So that's why I'm removing compaction here.

Same issue in the other test as well.

**Review by skyzh — APPROVED** [review]
LGTM, but I feel a better fix is to temporary add this keyspace to `collect_keyspace` in testing mode, or have some tests with both random update + compaction in the future.

**Comment by arpad-m** [comment]
> I feel a better fix is to temporary add this keyspace to collect_keyspace in testing mode, or have some tests with both random update + compaction in the future.

Yeah it's not perfect, but I'm sure there is other tests in the testsuite which do updates plus compaction. Note that the purpose of the tests is not to test compaction, otherwise probably greater care would have been taken to make the keys show up in `collect_keyspace`.

If you know of a good mechanism to make the keys be included in `collect_keyspace`, feel free to suggest it.
