### PR TITLE
fix: hide token from logs

### LINKED ISSUE #4583: Do not log storage auth token
```
[2m2023-06-28T07:58:36.608367Z[0m [32m INFO[0m [1mstart_compute[0m[2m:[0m[1mstart_postgres[0m[1m{[0m[3mstorage_auth_token[0m[2m=[0mSome("**************************")[1m}[0m[2m:[0m[1mwait_for_postgres[0m[1m{[0m[3mpgdata[0m[2m=[0m"/var/db/postgres/compute/pgdata"[1m}[0m[2m:[0m PostgreSQL is now running, continuing to configure it
```

I've replaced the actual key with asterisks. We don't need to log such sensitive information.

## Environment
prod

### PR DESCRIPTION
**Pull request by koivunej**
fixes #4583 and also changes all needlessly arg listing places to use `skip_all`.

### CODE REVIEW

**Comment by koivunej** [comment]
We can haggle about the second commit, I think using `skip_all` is better style than enumerating most of the args.

**Review by vadim2404 — APPROVED** [review]

File: compute_tools/src/compute.rs [hunk 1]
```diff
@@ -235,7 +235,7 @@ impl ComputeNode {
 
     // Get basebackup from the libpq connection to pageserver using `connstr` and
     // unarchive it to `pgdata` directory overriding all its previous content.
-    #[instrument(skip(self, compute_state))]
+    #[instrument(skip_all)]
```
Comment (koivunej) [inline compute_tools/src/compute.rs:238]: Well, this was not a good change, should restore the `lsn`.

File: compute_tools/src/compute.rs [hunk 2]
```diff
@@ -380,7 +380,7 @@ impl ComputeNode {
 
     /// Start Postgres as a child process and manage DBs/roles.
     /// After that this will hang waiting on the postmaster process to exit.
-    #[instrument(skip(self))]
+    #[instrument(skip_all)]
```
Comment (koivunej) [inline compute_tools/src/compute.rs:383]: this was the actual fix.

File: compute_tools/src/compute.rs (hunk 1 above)
Comment (koivunej) [reply compute_tools/src/compute.rs]: fixed in [577f608](https://github.com/neondatabase/neon/pull/4584/commits/577f60893a9c84216f1345289109e222a8168b39)
