### PR TITLE
fix: on-demand downloads can outlive timeline shutdown

### LINKED ISSUE #7054: pageserver: panic with download while detaching
```
2024-03-07T14:48:03.788503Z  INFO attach{tenant_id=9a6122c5fe1f2ca225eff4334c5860bb shard_id=0000 gen=00000015}: activation attempt finished since_creation_millis=93 tenant_id=9a6122c5fe1f2ca225eff4334c5860bb shard_id=0000 activated_timelines=1 total_timelines=1 post_state="Active"

2024-03-07T14:48:13.833236Z  INFO request{method=PUT path=/v1/tenant/9a6122c5fe1f2ca225eff4334c5860bb/location_config request_id=39ceb22d-c0fc-40da-869b-934cc417c9e2}:upsert_location{tenant_id=9a6122c5fe1f2ca225eff4334c5860bb shard_id=0000}: Waiting for timelines...
2024-03-07T14:48:13.833195Z  INFO request{method=PUT path=/v1/tenant/9a6122c5fe1f2ca225eff4334c5860bb/location_config request_id=39ceb22d-c0fc-40da-869b-934cc417c9e2}:upsert_location{tenant_id=9a6122c5fe1f2ca225eff4334c5860bb shard_id=0000}: configuring tenant location to state Attached Single, gen=00000016

2024-03-07T14:48:42.882322Z ERROR wal_connection_manager{tenant_id=9a6122c5fe1f2ca225eff4334c5860bb shard_id=0000 timeline_id=fc246e35326606a7d234825fbfd5ce4c}:connection{node_id=64}:get_or_maybe_download{layer=000000000000000000000000000000000000-000000067F00004005000040590000007D8D__00000000014EE9E8-0000000094E9CBB1}:panic{thread=walreceiver worker location=pageserver/src/tenant/storage_layer/layer.rs:975:21}: post-condition failed: needs_download returned WrongSize { actual: 255603996, expected: 268451840 }

2024-03-07T14:48:16.668174Z  INFO request{method=PUT path=/v1/tenant/9a6122c5fe1f2ca225eff4334c5860bb/location_config request_id=39ceb22d-c0fc-40da-869b-934cc417c9e2}:upsert_location{tenant_id=9a6122c5fe1f2ca225eff4334c5860bb shard_id=0000}:timeline_shutdown{timeline_id=fc246e35326606a7d234825fbfd5ce4c freeze_and_flush=false}: task walreceiver for timeline 9a6122c5fe1f2ca225eff4334c5860bb/fc246e35326606a7d234825fbfd5ce4c completed

2024-03-07T14:48:16.669811Z  INFO request{method=PUT path=/v1/tenant/9a6122c5fe1f2ca225eff4334c5860bb/location_config request_id=39ceb22d-c0fc-40da-869b-934cc417c9e2}:upsert_location{tenant_id=9a6122c5fe1f2ca225eff4334c5860bb shard_id=0000}: removed EvictionsWithLowResidenceDuration with 9a6122c5fe1f2ca225eff4334c5860bb, fc246e35326606a7d234825fbfd5ce4c, mtime, 1200
2024-03-07T14:48:16.670586Z  INFO request{method=PUT path=/v1/tenant/9a6122c5fe1f2ca225eff4334c5860bb/location_config request_id=39ceb22d-c0fc-40da-869b-934cc417c9e2}: No flush requested when configuring
2024-03-07T14:48:16.670644Z  INFO attach{tenant_id=9a6122c5fe1f2ca225eff4334c5860bb shard_id=0000 gen=00000016}:preload: listing remote timelines
2024-03-07T14:48:16.670629Z  INFO attach{tenant_id=9a6122c5fe1f2ca225eff4334c5860bb shard_id=0000 gen=00000016}: Attaching tenant attach_mode=Single
2024-03-07T14:48:16.670627Z  INFO request{method=PUT path=/v1/tenant/9a6122c5fe1f2ca225eff4334c5860bb/location_config request_id=39ceb22d-c0fc-40da-869b-934cc417c9e2}: Request handled, status: 200 OK
```

Otherwise this would be quite clear situation, except that the length is wrong. The expected length is correct, the same file had been previously downloaded.

Already noticed problems during #7030, timeline gate should be entered for the download.

### PR DESCRIPTION
**Pull request by koivunej**
## Problem

Before this PR, it was possible that on-demand downloads were started after `Timeline::shutdown()`.

For example, we have observed a walreceiver-connection-handler-initiated on-demand download that was started after `Timeline::shutdown()`s final `task_mgr::shutdown_tasks()` call.

The underlying issue is that `task_mgr::shutdown_tasks()` isn't sticky, i.e., new tasks can be spawned during or after `task_mgr::shutdown_tasks()`.

Cc: https://github.com/neondatabase/neon/issues/4175 in lieu of a more specific issue for task_mgr. We already decided we want to get rid of it anyways.

Original investigation: https://neondb.slack.com/archives/C033RQ5SPDH/p1709824952465949

## Changes

- enter gate while downloading
- use timeline cancellation token for cancelling download

thereby, fixes #7054

Entering the gate might also remove recent "kept the gate from closing" in staging.

### CODE REVIEW

File: pageserver/src/tenant/storage_layer/layer.rs [hunk 1]
```diff
@@ -880,23 +880,18 @@ impl LayerInner {
...
         let (tx, rx) = tokio::sync::oneshot::channel();
 
-        // this is sadly needed because of task_mgr::shutdown_tasks, otherwise we cannot
-        // block tenant::mgr::remove_tenant_from_memory.
-
         let this: Arc<Self> = self.clone();
 
-        crate::task_mgr::spawn(
-            &tokio::runtime::Handle::current(),
-            crate::task_mgr::TaskKind::RemoteDownloadTask,
```
Comment (problame) [inline pageserver/src/tenant/storage_layer/layer.rs:894]: We can remove that TaskKind from task_mgr.rs

File: pageserver/src/tenant/storage_layer/layer.rs [hunk 2]
```diff
@@ -880,23 +880,18 @@ impl LayerInner {
     ) -> Result<heavier_once_cell::InitPermit, DownloadError> {
         debug_assert_current_span_has_tenant_and_timeline_id();
 
-        let task_name = format!("download layer {}", self);
-
         let (tx, rx) = tokio::sync::oneshot::channel();
 
-        // this is sadly needed because of task_mgr::shutdown_tasks, otherwise we cannot
-        // block tenant::mgr::remove_tenant_from_memory.
```
Comment (problame) [inline pageserver/src/tenant/storage_layer/layer.rs:888]: Did we think this through when we decided to remove task_mgr::spawn? I think so ?

**Review by problame — APPROVED** [review]

File: pageserver/src/tenant/storage_layer/layer.rs (hunk 2 above)
Comment (koivunej) [reply pageserver/src/tenant/storage_layer/layer.rs:888]: Yes, it's the gate which allows this.

File: pageserver/src/tenant/storage_layer/layer.rs (hunk 1 above)
Comment (koivunej) [reply pageserver/src/tenant/storage_layer/layer.rs:894]: Good idea to clean it up as well. Weird no warning again...?

Comment (koivunej) [reply pageserver/src/tenant/storage_layer/layer.rs:894]: No warning because it is `pub`, used by requestcontext task_mgr::spawn from `pageserver/src/bin/pageserver.rs`.

Comment (koivunej) [reply pageserver/src/tenant/storage_layer/layer.rs:894]: https://github.com/neondatabase/neon/pull/7051/commits/84fff41e2422c77fb63a0319017795a4a5cbefd4

**Comment by koivunej** [comment]
> #### Failures on Postgres 14
> 
>     * `test_delete_tenant_exercise_crash_safety_failpoints[real_s3-tenant-delete-before-shutdown-False-Check.RETRY_WITH_RESTART]`: [debug](https://neon-github-public-dev.s3.amazonaws.com/reports/pr-7051/8203529232/index.html#suites/3556ed71f2d69272a7014df6dcb02317/a77db72dd3c262a5)

This does not sound like something which should be happening. There is no logging for 5s:

```
2024-03-08T13:15:22.269909Z  INFO shutdown_pageserver{exit_code=0}: completed stage="shutdown all tenants" elapsed_ms=1
2024-03-08T13:15:22.269933Z  INFO shutdown_pageserver{exit_code=0}: completed stage="shutdown PageRequestHandlers" elapsed_ms=0
2024-03-08T13:15:27.271529Z  WARN shutdown_pageserver{exit_code=0}: Timed out flushing deletion queue on shutdown
2024-03-08T13:15:27.272364Z  INFO shutdown_pageserver{exit_code=0}: completed stage="shutdown http" elapsed_ms=0
```

But maybe it was stuck because of a failpoint?

**Comment by koivunej** [comment]
> Entering the gate might also remove recent "kept the gate from closing" in staging.

These were [log search](https://neonprod.grafana.net/explore?schemaVersion=1&panes=%7B%22shf%22:%7B%22datasource%22:%22xHHYY0dVz%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bneon_service%3D%5C%22pageserver%5C%22%7D%20%7C%3D%20%60kept%20the%20gate%20from%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22xHHYY0dVz%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221709819877029%22,%22to%22:%221709839684144%22%7D%7D%7D&orgId=1) like:

```
2024-03-07T14:37:42.351943Z  INFO page_service_conn_main{peer_addr=10.10.17.246:51762}:process_query{tenant_id=9a6122c5fe1f2ca225eff4334c5860bb timeline_id=fc246e35326606a7d234825fbfd5ce4c}:handle_pagerequests:handle_get_page_at_lsn_request{rel=1663/16389/16473 blkno=6815 req_lsn=0/C25DDF50}:handle_get_page_at_lsn_request{shard_id=0000}: kept the gate from closing gate=0x7fd9a0208040
```

This was gate was held open because of an on-demand download -- the handle_get_page_at_lsn_request already takes a gate, but not cancelled because of timeline was cancelled.

**Comment by koivunej** [comment]
> I have a feeling the same warning should happen from other tests.

Since this happened now more than 0 times, I think this should be good to merge.
