### PR TITLE
Don't propagate but log file not found error in layer uploading

### LINKED ISSUE #4526: failed to perform remote task UploadLayer No such file or directory
## Steps to reproduce

Judging by logs flush_loop iteration that is close to (or even interleaved with) compaction lead to that

## Expected result

No error

## Actual result
Error no such file or directory.

## Environment
prod

## Logs, links
- More condensed version that includes only events with relevant layer file
[Explore-logs-2023-06-16 12_15_36.txt](https://github.com/neondatabase/neon/files/11770069/Explore-logs-2023-06-16.12_15_36.txt)
- Full log for that tenant for the relevant time-frame (just for completeness)
[Explore-logs-2023-06-16 12_05_00.txt](https://github.com/neondatabase/neon/files/11770045/Explore-logs-2023-06-16.12_05_00.txt)

At a quick glance it should be harmless because if we deleted the layer locally it means that we scheduled the upload of a covering one, so there shouldnt be any data loss. But it needs more in-depth look.

### PR DESCRIPTION
**Pull request by arpad-m**
## Problem

This addresses the issue in #4526 by adding a test that reproduces the race condition that gave rise to the bug (or at least *a* race condition that gave rise to the same error message), and then implementing a fix that just prints a message to the log if a file could not been found for uploading. Even though the underlying race condition is not fixed yet, this will un-block the upload queue in that situation, greatly reducing the impact of such a (rare) race.

Fixes #4526.

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.
- [ ] Do we need to implement analytics? if so did you add the relevant metrics to the dashboard?
- [ ] If this PR requires public announcement, mark it with /release-notes label and add several sentences in this section.

## Checklist before merging

- [ ] Do not forget to reformat commit message to not include the above checklist

### CODE REVIEW

File: pageserver/src/tenant/remote_timeline_client/upload.rs [hunk 1]
```diff
@@ -56,9 +58,22 @@ pub(super) async fn upload_timeline_layer<'a>(
...
+    let source_file_res = fs::File::open(&source_path).await;
+    let source_file = match source_file_res {
+        Ok(source_file) => source_file,
+        Err(e) if e.kind() == ErrorKind::NotFound => {
+            // In some situations we might run into the underlying file being deleted by
+            // e.g. compaction before the uploader gets to it. In that instance, we don't
+            // want to retry the error: a deleted file won't come back. In theory, the
+            // file might not have been written in the first place, which also indicates
+            // a bug. Still log the situation so that we can keep an eye on it.
+            // See https://github.com/neondatabase/neon/issues/4526
```
Comment (koivunej) [inline pageserver/src/tenant/remote_timeline_client/upload.rs:70]: In general we are quite good on writing stuff to disk *before* scheduling an upload.

However ... wondering do we need this much text because we also log. From the point of view of remote_timeline_client, this is very much a persistent failure and we can't do anything about it.

On the actual site of the race, we could add some "FIXME: between `create_delta_layer` and scheduling an upload, a compaction could come in and delete the file". Mentioning that, I was thinking we would have sort of preconditions on scheduling a file upload, that you couldn't schedule a not found path, but I guess we don't have such? Confirmed we don't. Unsure if that is actionable.

File: test_runner/regress/test_remote_storage.py [hunk 2]
```diff
@@ -777,6 +777,103 @@ def create_in_background():
...
+        except PageserverApiException as e:
+            q.put(e)
+
+    create_thread = threading.Thread(target=checkpoint_in_background)
+    create_thread.start()
+
+    try:
+        barrier.wait()
+
+        time.sleep(4)
```
Comment (shanyp) [inline test_runner/regress/test_remote_storage.py:855]: compaction_threshold +1 ?

File: test_runner/regress/test_remote_storage.py [hunk 3]
```diff
@@ -777,6 +777,103 @@ def create_in_background():
...
+            # Disable GC
+            "gc_period": "0s",
+            # disable PITR
+            "pitr_interval": "0s",
+        }
+    )
+
+    client = env.pageserver.http_client()
+
+    endpoint = env.endpoints.create_start("main", tenant_id=tenant_id)
```
Comment (koivunej) [inline test_runner/regress/test_remote_storage.py:810]: In general I would always prefer 
```suggestion
    with env.endpoints.create_start("main", tenant_id=tenant_id) as endpoint:
        # everything up to:
    
    q: queue.Queue[...] = ...
```

Because leaving the compute running opens up a chance of it producing more WAL, which has been a cause of a flakyness in some tests. However this test is not sensitive to that, because we are interested in the single checkpoint + compaction pair.

But this is something to keep in mind. I'll suggest something else to make this a bit smaller one.

File: test_runner/regress/test_remote_storage.py [hunk 4]
```diff
@@ -777,6 +777,103 @@ def create_in_background():
...
+
+    # Build two tables with some data inside
+    endpoint.safe_psql_many(
+        [
+            "CREATE TABLE foo (x INTEGER)",
+            "INSERT INTO foo SELECT g FROM generate_series(1, 10000) g",
+        ]
+    )
```
Comment (koivunej) [inline test_runner/regress/test_remote_storage.py:818]:
```suggestion
    endpoint.safe_psql(
        "CREATE TABLE foo AS SELECT x FROM generate_series(1, 10000) g(x)",
    )
```

Unsure how python wants to format that, we have `scripts/format` for this purpose, forgot to mention it earlier.

File: test_runner/regress/test_remote_storage.py [hunk 5]
```diff
@@ -777,6 +777,103 @@ def create_in_background():
...
+
+        client.configure_failpoints(("flush-frozen-before-sync", "off"))
+
+        conflict = q.get()
+
+        assert conflict is None
+    finally:
+        create_thread.join()
+
+    time.sleep(4)
```
Comment (koivunej) [inline test_runner/regress/test_remote_storage.py:866]:
```suggestion
    # add a delay for the uploads to get stuck on file not found or to complete.
    time.sleep(4)
```

As in, we could explain reason for the sleep as it does look quite suspicious.

File: pageserver/src/tenant/remote_timeline_client/upload.rs (hunk 1 above)
Comment (shanyp) [reply pageserver/src/tenant/remote_timeline_client/upload.rs:70]: I think that if this is not actionable, we can either remove the log or move it to trace level

File: pageserver/src/tenant/timeline.rs [hunk 6]
```diff
@@ -2918,7 +2918,20 @@ impl Timeline {
...
+                let current = tracing::Span::current();
+                move || {
+                    let _entered = current.entered();
+                    tracing::info!("at failpoint flush-frozen-before-sync");
+                    fail::fail_point!("flush-frozen-before-sync");
+                }
+            })
+            .await
+            .expect("spawn_blocking");
+        }
```
Comment (shanyp) [inline pageserver/src/tenant/timeline.rs:2934]: can this repeated code could be factored to some kind of macro ?

creat_fail_point!("flush-frozen-before-sync")
 ?

File: test_runner/regress/test_remote_storage.py [hunk 7]
```diff
@@ -777,6 +777,103 @@ def create_in_background():
...
+
+    # Ensure that this actually terminates
+    wait_upload_queue_empty(client, tenant_id, timeline_id)
+
+    # For now we are hitting this message.
+    # Maybe in the future the underlying race condition will be fixed,
+    # but until then, ensure that this message is hit instead.
+    assert env.pageserver.log_contains("for upload, assuming an upload is not required any more.")
```
Comment (shanyp) [inline test_runner/regress/test_remote_storage.py:874]: I don't see see tracing, did you mean "Likely the file was deleted before and an upload"

File: pageserver/src/tenant/remote_timeline_client/upload.rs (hunk 1 above)
Comment (koivunej) [reply pageserver/src/tenant/remote_timeline_client/upload.rs:70]: > we can either remove the log or move it to trace level

Aah agreed yeah ... Yeah, perhaps we should make it into a `debug`, as we cannot do anything. We still see the layer being flushed, and layer being deleted by compaction in the logs, we just wouldn't see the (later) error at all about it not being uploaded.

File: test_runner/regress/test_remote_storage.py (hunk 2 above)
Comment (koivunej) [reply test_runner/regress/test_remote_storage.py:855]: To fill in what I remember; it was needed so that the timeline_checkpoint has enough time to write out the delta layer and hit the failpoint. Elsewhere in tests there are examples of `wait_until` loops checking if the log has "at failpoint xxyyzz".

Comment (arpad-m) [reply test_runner/regress/test_remote_storage.py:844]: I think the idea of this sleep is to ensure ordering, to have the compaction on the main thread run after the other thread's compaction has already started (but I don't have complete understanding of this). So four is just a random number, 3 works too.

The error it gives if you remove the sleep is:

```
FAILED test_runner/regress/test_remote_storage.py::test_compaction_delete_before_upload[debug-pg14-local_fs] - assert None
```

File: pageserver/src/tenant/remote_timeline_client/upload.rs (hunk 1 above)
Comment (arpad-m) [reply pageserver/src/tenant/remote_timeline_client/upload.rs:70]: I have not looked it up on grafana but IIRC the race occurs only very rarely? It's just that before it blocked the upload queue so each time it happened it had a non trivial impact.

I think it is useful to have at least some message here. In the future due to some rearchitecting it might occur that we delete files that are actually still useful and then we might wonder why, even though they are scheduled for upload, are not uploaded.

I mean in theory the uploader might also be given wrong file names, and that's why they don't exist, or the files haven't been written to disk yet. Or there has been a restart and the filesystem with the layer files is not mounted yet, etc (in the future one might want to do that, I'm not saying it should be done, just that we are ideally future proof here).

**Review by shanyp — APPROVED** [review]
